"""File containing strings used in hsm.

Note
----
Convention for import alias is,
import names as nam

"""

### HSM Setup variables
can_setup                   = 'can_setup'
off_setup                   = 'off_setup'
on_setup                    = 'on_setup'
ak_setup                    = 'ak_setup'
ngp_setup                   = 'ngp_setup'
hist_setup                  = 'hist_setup'
steo_setup                  = 'steo_setup'
canada_switch               = 'canada_switch'
offshore_switch             = 'offshore_switch'
onshore_switch              = 'onshore_switch'
alaska_switch               = 'alaska_switch'
ngp_switch                  = 'ngp_switch'
discounting                 = 'discounting'
mapping                     = 'mapping'
hdf_full_restart_int        = 'hdf_full_restart_int'


###Historical Tables
hist_rfqtdcrd   = 'hist_rfqtdcrd'
hist_ogqshloil  = 'hist_ogqshloil'
hist_ogqshlgas  = 'hist_ogqshlgas'
hist_ngplprd    = 'hist_ngplprd'
hist_htowells   = 'hist_htowells'
hist_htoilprd   = 'hist_htoilprd'
hist_htgwells   = 'hist_htgwells'
hist_htgasprd   = 'hist_htgasprd'
hist_htadgprd   = 'hist_htadgprd'
hist_hsgwells   = 'hist_hsgwells'
hist_hsgasprd   = 'hist_hsgasprd'
hist_hoilres    = 'hist_hoilres'
hist_hgasres    = 'hist_hgasres'
hist_hdryholes  = 'hist_hdryholes'
hist_hcowells   = 'hist_hcowells'
hist_hcoilprd   = 'hist_hcoilprd'
hist_hcgwells   = 'hist_hcgwells'
hist_hcgasprd   = 'hist_hcgasprd'
hist_hcbmwells  = 'hist_hcbmwells'
hist_hcbmprd    = 'hist_hcbmprd'
hist_hcadgprd   = 'hist_hcadgprd'
hist_ognowell   = 'hist_ognowell'
hist_eplp       = 'hist_eplp'
hist_epllpa     = 'hist_epllpa'
hist_epllea     = 'hist_epllea'
hist_epllban    = 'hist_epllban'
hist_epllbai    = 'hist_epllbai'
hist_epl2       = 'hist_epl2'
hist_dcrdwhp    = 'hist_dcrdwhp'
hist_eor_prod   = 'hist_eor_prod'
hist_crude_lfmm = 'hist_crude_lfmm'


###STEO Tables
steo_dcrdwhp            = 'steo_dcrdwhp'
steo_ogngplbu           = 'steo_ogngplbu'
steo_ogngplet           = 'steo_ogngplet'
steo_ogngplis           = 'steo_ogngplis'
steo_ogngplpp           = 'steo_ogngplpp'
steo_ogngplpr           = 'steo_ogngplpr'
steo_ogngplprd          = 'steo_ogngplprd'
steo_rfqtdcrd           = 'steo_rfqtdcrd'
steo_togqshlgas         = 'steo_togqshlgas'
steo_togqshloil         = 'steo_togqshloil'
steo_ogadgprd           = 'steo_ogadgprd'
steo_ogenagprd          = 'steo_ogenagprd'
steo_owrite_can         = 'steo_owrite_can'
steo_owrite_ngpls       = 'steo_owrite_ngpls'
steo_owrite_rfqtdcrd    = 'steo_owrite_rfqtdcrd'
steo_owrite_ad_ng       = 'steo_owrite_ad_ng'
steo_owrite_na_ng       = 'steo_owrite_na_ng'



###NGPL History and STEO Ratios
ngpl_region_number  = 'ngpl_region_number'
ngpl_region_name    = 'ngpl_region_name'
ngpl_region_sum     = 'ngpl_region_sum'
ngpl_share_ratio    = 'ngpl_share_ratio'
total_ngpls         = 'total_ngpls'
ethane              = 'ethane'
propane             = 'propane'
butane              = 'butane'
isobutane           = 'isobutane'
pentanes_plus       = 'pentanes_plus'


###Cash_flow submodule variables
year    = 'year'

# input tables
depreciation_schedules  = 'depreciation_schedules'
state_tax_table         = 'state_tax_table'

# property and property column names
properties          = 'properties'
crude_price         = 'crude_price'
natgas_price        = 'natgas_price'
ngpl_price          = 'ngpl_price'
crude_trans_price   = 'crude_trans_price'
natgas_trans_price  = 'natgas_trans_price'
crude_tariff_price  = 'crude_tariff_price'
natgas_tariff_price = 'natgas_tariff_price'
royalty_rate        = 'royalty_rate'
project_royalty_multiplier = 'project_royalty_multiplier'
exp_success_rate    = 'exp_success_rate'
dev_success_rate    = 'dev_success_rate'
exp_well_price      = 'exp_well_price'
dev_well_price      = 'dev_well_price'
exp_dry_well_price  = 'exp_dry_well_price'
dev_dry_well_price  = 'dev_dry_well_price'
exp_tang_frac       = 'exp_tang_frac'
dev_tang_frac       = 'dev_tang_frac'
kap_tang_frac       = 'kap_tang_frac'
intang_amor_frac    = 'intang_amor_frac'
amor_schedule       = 'amor_schedule'
deprec_schedule     = 'deprec_schedule'
abandon_rate        = 'abandon_rate'
state_tax_rate      = 'state_tax_rate'
fed_tax_rate        = 'fed_tax_rate'
discount_rate       = 'discount_rate'
eor_tc_rate         = 'eor_tc_rate'
eor_tc_phaseout     = 'eor_tc_phaseout'
econ_life           = 'econ_life'
net_present_value   = 'net_present_value'
capital_cost        = 'capital_cost'
profitability       = 'profitability'
existing_45q        = 'existing_45q'
existing_ntc        = 'existing_ntc'
retrofit_status     = 'retrofit_status'

# production and revenue DataFrame names
crude_production    = 'crude_production'
natgas_production   = 'natgas_production'
crude_revenue       = 'crude_revenue'
natgas_revenue      = 'natgas_revenue'
revenue             = 'revenue'

# transportation DataFrame names
crude_trans     = 'crude_trans'
natgas_trans    = 'natgas_trans'
transportation  = 'transportation'

# royalty DataFrame names
crude_royalty   = 'crude_royalty'
natgas_royalty  = 'natgas_royalty'
royalty         = 'royalty'

# severance DataFrame names
sev_rate_crude_rev      = 'sev_rate_crude_rev'
sev_rate_natgas_rev     = 'sev_rate_natgas_rev'
sev_rate_crude_prod     = 'sev_rate_crude_prod'
sev_rate_natgas_prod    = 'sev_rate_natgas_prod'
severance_tax           = 'severance_tax'

# drill cost DataFrame names
drill_cost      = 'drill_cost'
exp_schedule    = 'exp_schedule'
dev_schedule    = 'dev_schedule'
exp_drill_cost  = 'exp_drill_cost'
dev_drill_cost  = 'dev_drill_cost'
exp_dry_cost    = 'exp_dry_cost'
dev_dry_cost    = 'dev_dry_cost'

# tangible and intangible costs
intang_cost     = 'intang_cost'
tang_cost       = 'tang_cost'
dry_hole_cost   = 'dry_hole_cost'

# depletion, amortization, and depletion
depreciation_method = 'depreciation_method'
general_admin_cost  = 'general_admin_cost'
tangible_adjustment = 'tangible_adjustment'
expn_intang_cost    = 'expn_intang_cost'
amor_intang_cost    = 'amor_intang_cost'
deprec_tang_cost    = 'deprec_tang_cost'
depletion           = 'depletion'

# economic limit DataFrame names
fed_credit      = 'fed_credit'
operating_cost  = 'operating_cost'
equip_cost      = 'equip_cost'
econ_limit      = 'econ_limit'

# abandonment DataFrame names
abandon_cost        = 'abandon_cost'

# state tax DataFrame names
tax_base_state      = 'tax_base_state'
state_tax           = 'state_tax'

# federal tax DataFrame names
eor_tax_credit  = 'eor_tax_credit'
invest_credit   = 'invest_credit'
tax_base_fed    = 'tax_base_fed'
fed_tax         = 'fed_tax'

# cash_flow DataFrame names
kap_cost    = 'kap_cost'
gg_la_cost  = 'gg_la_cost'
cash_flow   = 'cash_flow'

# variables for testing
array       = 'array'
function    = 'function'
iecon       = 'iecon'       # OOGSS exploratory and development flag, should split into to instances of cash_flow

# regional variables
state_abbreviation  = 'state_abbreviation'
state               = 'state'
ocs                 = 'OCS'
state_name          = 'state_name'


###Common Variables

#Weighted Average Cost of Capital Variables
debt_ratio                  = 'debt_ratio'
industry_beta               = 'industry_beta'
market_risk_premium         = 'market_risk_premium'
return_over_capital_cost    = 'return_over_capital_cost'


###Onshore Variables

#Onshore input
on_zero_year                        = 'on_zero_year'
on_final_year                       = 'on_final_year'
on_drilling_cost_base               = 'on_drilling_cost_base'
on_averaging_years                  = 'on_averaging_years'
on_royalty_rate                     = 'on_royalty_rate'
on_base_oil_prc                     = 'on_base_oil_prc'
on_cut_oil_prc                      = 'on_cut_oil_prc'
on_base_gas_prc                     = 'on_base_gas_prc'
on_oil_exp_tang_frac                = 'on_oil_exp_tang_frac'
on_oil_dev_tang_frac                = 'on_oil_dev_tang_frac'
on_gas_exp_tang_frac                = 'on_gas_exp_tang_frac'
on_gas_dev_tang_frac                = 'on_gas_dev_tang_frac'
on_kap_tang_frac                    = 'on_kap_tang_frac'
on_amor_schedule                    = 'on_amor_schedule'
on_deprec_schedule                  = 'on_deprec_schedule'
on_intang_amor_frac                 = 'on_intang_amor_frac'
on_abandon_rate                     = 'on_abandon_rate'
on_drill_ramp_up                    = 'on_drill_ramp_up'
on_drill_predecline                 = 'on_drill_predecline'
on_cost_tech_rate                   = 'on_cost_tech_rate'
on_constraint_tech_rate             = 'on_constraint_tech_rate'
on_old_process_code_conv            = 'on_old_process_code_conv'
on_discovery_order                  = 'on_discovery_order'
on_drill_cost_eqs                   = 'on_drill_cost_eqs'
on_basin_avg_cost                   = 'on_basin_avg_cost'
on_region_avg_cost                  = 'on_region_avg_cost'
on_process_codes                    = 'on_process_codes'
on_drill_eq_constraints             = 'on_drill_eq_constraints'
on_drilling_costs                   = 'on_drilling_costs'
on_evaluation_years                 = 'on_evaluation_years'
on_projects_continuous              = 'on_projects_continuous'
on_projects_producing_gas           = 'on_projects_producing_gas'
on_projects_producing_oil           = 'on_projects_producing_oil'
on_projects_other_eor               = 'on_projects_other_eor'
on_projects_co2_eor                 = 'on_projects_co2_eor'
on_projects_undiscovered            = 'on_projects_undiscovered'
on_legacy_co2_costs                 = 'on_legacy_co2_costs'
on_ngpl_costs                       = 'on_ngpl_costs'
on_co2_pipe_seg_costs               = 'on_co2_pipe_seg_costs'
on_select_plays                     = 'on_select_plays'
on_dryhole_rate                     = 'on_dryhole_rate'
on_eor_other_costs                  = 'on_eor_other_costs'
on_eor_trans_factors                = 'on_eor_trans_factors'
on_co2_supply_cost_temp             = 'on_co2_supply_cost_temp'
on_footage_constraint_eq            = 'on_footage_constraint_eq'
on_rig_constraint_eq                = 'on_rig_constraint_eq'
on_capital_constraint_eq            = 'on_capital_constraint_eq'
on_constraint_params                = 'on_constraint_params'
on_wells_per_rig                    = 'on_wells_per_rig'
on_tech_levers                      = 'on_tech_levers'
on_eor_tc_rate                      = 'on_eor_tc_rate'
on_eor_tc_phaseout                  = 'on_eor_tc_phaseout'
on_co2_trans_cost                   = 'on_co2_trans_cost'
on_ch4_emission_factors_basin       = 'on_ch4_emission_factors_basin'
hsm_on_projects                     = 'hsm_on_projects'
hsm_on_projects_undiscovered        = 'hsm_on_projects_undiscovered'
hsm_on_crude_production             = 'hsm_on_crude_production'
hsm_on_natgas_production            = 'hsm_on_natgas_production'
hsm_on_ngpl_production              = 'hsm_on_ngpl_production'
hsm_on_ngpl_ethane_production       = 'hsm_on_ngpl_ethane_production'
hsm_on_ngpl_propane_production      = 'hsm_on_ngpl_propane_production'
hsm_on_ngpl_butane_production       = 'hsm_on_ngpl_butane_production'
hsm_on_ngpl_isobutane_production    = 'hsm_on_ngpl_isobutane_production'
hsm_on_ngpl_proplus_production      = 'hsm_on_ngpl_proplus_production'
hsm_on_wells                        = 'hsm_on_wells'
hsm_on_producing_wells              = 'hsm_on_producing_wells'
hsm_on_producing_footage            = 'hsm_on_producing_footage'
hsm_on_dryholes                     = 'hsm_on_dryholes'
hsm_on_exploratory_wells            = 'hsm_on_exploratory_wells'
hsm_on_eor_cum_prod                 = 'hsm_on_eor_cum_prod'
hsm_on_co2_purchased                = 'hsm_on_co2_purchased'
hsm_on_co2_used                     = 'hsm_on_co2_used'
hsm_on_co2_injected                 = 'hsm_on_co2_injected'
hsm_on_co2_recycled                 = 'hsm_on_co2_recycled'
hsm_on_co2_available                = 'hsm_on_co2_available'


# Onshore Switches
play_map_switch = 'play_map_switch'



#Model Process Variables
base_year                   = 'base_year'
base_price_year             = 'base_price_year'
price_year                  = 'price_year'
technology_year             = 'technology_year'
aeo_year                    = 'aeo_year'
history_year                = 'history_year'
final_aeo_year              = 'final_aeo_year'
mnumor                      = 'mnumor'
run_every_itr_switch        = 'run_every_itr_switch'
steo_benchmark_adj_switch   = 'steo_benchmark_adj_switch'
debug_switch                = 'debug_switch'
hsm_var_debug_switch        = 'hsm_var_debug_switch'


#Classification Variables
resid                       = 'resid'
eor_resid                   = 'eor_resid'
play                        = 'play'
hsm_index                   = 'hsm_index'
flag                        = 'flag'
process_code                = 'process_code'
usgs_province_num           = 'usgs_province_num'
usgs_province_num_merge     = 'usgs_province_num_merge'
gas_type_number             = 'gas_type_number'
gas_type                    = 'gas_type'
district_number             = 'district_number'
district                    = 'district'
census_division             = 'census_division'
rrc_number                  = 'rrc_number'
region_number               = 'region_number'
region_name                 = 'region_name'
lfmm_region_number          = 'lfmm_region_number'
lfmm_region_name            = 'lfmm_region_name'
lfmm_crude_type             = 'lfmm_crude_type'
ngpl_type                   = 'ngpl_type'
padd                        = 'padd'
api                         = 'API'
avg_api                     = 'avg_api'
sulfur                      = 'Sulfur'
crude_heat                  = 'crude_heat'
federal_land                = 'federal_land'
crude_type_number           = 'crude_type_number'
crude_type_name             = 'crude_type_name'
gas_types                   = 'gas_types'
well_type                   = 'well_type'
well_type_merge             = 'well_type_merge'
well_type_number            = 'well_type_number'
oil_type_number             = 'oil_type_number'
oil_type                    = 'oil_type'
dev_type_number             = 'dev_type_number'
table                       = 'table'
old_process_codes           = 'old_process_codes'
old_flag                    = 'old_flag'
prod_tier                   = 'prod_tier'
oil_category                    = 'oil_category'
gas_category                = 'gas_category'


#Project Input Types
continuous                  = 'continuous'
producing_gas               = 'producing_gas'
producing_oil               = 'producing_oil'
other_eor                   = 'other_eor'
co2_eor                     = 'co2_eor'
undiscovered                = 'undiscovered'


#General variables
filename    = 'filename'
value       = 'value'
variable    = 'variable'


#Drilling EQ Variables
hist_year_wells             = 'Ninjwell'
hist_year_wells_2           = 'Ngaswell'
resacc                      = 'resacc'
total_pattern_size_acres    = 'total_pattern_size_acres'
std_pattern_size_acres      = 'std_pattern_size_acres'
past_wells                  = 'past_wells'
well_limit                  = 'well_limit'
max_wells                   = 'max_wells'
min_well_spacing            = 'min_well_spacing'
max_lat_len_spacing         = 'max_lat_len_spacing'
remaining_wells             = 'remaining_wells'
max_drill_rate              = 'max_drill_rate'
max_drill_rate_frac         = 'max_drill_rate_frac'
max_drill_rate_pct          = 'max_drill_rate_%'
max_year_drill_pct          = 'max_year_drill_%'
min_drill_totpat_pct        = 'min_drill_totpat_%'
max_annual_pct_dev          = 'max_annual_%_dev'
hist_well_drill_pct         = 'hist_year_well_drill_%'
min_annual_wells            = 'min_annual_wells'
dryhole_rate                = 'dryhole_rate'
drill_predecline            = 'drill_predecline'
crude_price_lag             = 'oil_price_lag'
natgas_price_lag            = 'natgas_price_lag'
prime_fuel_type_number      = 'prime_fuel_type_number'
totpat                      = 'totpat'
cum_oil_prod                = 'cum_oil_prod'
cum_gas_prod                = 'cum_gas_prod'
remaining_oil_resources     = 'remaining_oil_resources'
remaining_gas_resources     = 'remaining_gas_resources'
projected_und_wells         = 'projected_und_wells'
dryholes                    = 'dryholes'
lat_len_test                = 'lat_len_test'


#Cost EQ Variables
brent_price             = 'brent_price'
cost_type               = 'cost_type'
production_opex_brl     = 'production_opex_brl'
transport_opex_brl      = 'transport_opex_brl'
sga_opex_well           = 'sga_opex_well'
facility_capex_well     = 'facility_capex_well'
gg_lease_capex_well     = 'gg_lease_capex_well'
cost_1987_usd           = 'cost_1987_usd'
capex_well              = 'capex_well'
resource_type           = 'resource_type'
fuel_type_num           = 'fuel_type_num'
fuel_type_name          = 'fuel_type_name'
drill_depth_ft          = 'drill_depth_ft'
lateral_length_ft       = 'lateral_length_ft'
num_vfeet               = 'num_vfeet'
num_latlen              = 'num_latlen'
hist_cost_quantile_99   = 'hist_cost_quantile_99'
hist_cost_quantile_01   = 'hist_cost_quantile_01'
coef_name               = 'coef_name'
coef                    = 'coef'
std_err                 = 'std err'
t                       = 't'
p_val                   = 'p_val'
low_con_int             = 'low_con_int(0.025)'
high_con_int            = 'high_con_int (0.975)'
base_year               = 'base_year'
year_seq                = 'year_seq'
usgs_province_coef      = 'usgs_province_coef'
state_coef              = 'state_coef'
depth                   = 'Depth'
v_depth                 = 'v_depth'
lat_length              = 'lat_length'
crude_prod_mean         = 'crude_prod_mean'
natgas_prod_mean        = 'natgas_prod_mean'
term                    = 'term'
term_mult               = 'term_mult'
temp_total_patterns     = 'temp_total_patterns'
drill_category          = 'drill_category'
last_year_drilling_sort = 'last_year_drilling_sort'
ch4_emission_factor     = 'ch4_emission_factor'
ch4_emission_cost       = 'ch4_emission_cost'


#Technology Variables
drill_tech      = 'drill_tech'
cost_tech       = 'cost_tech'
eur_tech        = 'eur_tech'
tier_1_eur_tech	= 'tier_1_eur_tech'
tier_2_eur_tech	= 'tier_2_eur_tech'
spacing_tech    = 'spacing_tech'


#NGPL Variables
ngpl_volume     = 'ngpl_volume'
ngpl_cost       = 'ngpl_cost'
ngpl_opex       = 'ngpl_opex'
ngpl_capex      = 'ngpl_capex'
ngpl             = 'NGPL'
denom           = 'denom'
thru            = 'THRU'
capacity_st     = 'CAPST'
capacity_cr     = 'CAPCR'
gpm_val         = 'gpm_val'
weight_a        = 'weight_a'
weight_b        = 'weight_b'
str_plant_capex = 'str_plant_capex'
cry_plant_capex = 'cry_plant_capex'
str_plant_opex  = 'str_plant_opex'
cry_plant_opex  = 'cry_plant_opex'


#EOR/ASR Variables
eor_type                = 'eor_type'
eligible                = 'eligible'
var_type                = 'var_type'
co2_cost                = 'co2_cost'
co2_type                = 'co2_type'
co2_price               = 'co2_price'
co2_transport           = 'co2_transport'
co2_transport_cost      = 'co2_transport_cost'
water_plant_cost        = 'water_plant_cost'
co2_recy_plant_cost     = 'co2_recy_plant_cost'
water_max               = 'water_max'
water_handling_plant    = 'water_handling_plant'
co2_recycle_cost        = 'co2_recycle_cost'
bench_1                 = 'bench_1'
bench_2                 = 'bench_2'
bench_oil               = 'bench_oil'
bin                     = 'bin'
source_num              = 'source_num'
supply                  = 'supply'
price                   = 'price'
mmt                     = 'mmt'
d_tonne                 = 'd_tonne'
eor_45q_credit          = 'eor_45q_credit'


#Constraint Variables
wells                       = 'wells'
rigs                        = 'rigs'
footage                     = 'footage'
exp_ratio                   = 'exp_ratio'
producing_rigs              = 'producing_rigs'
producing_footage           = 'producing_footage'
neg_npv_tally               = 'neg_npv_tally'
wells_projected             = 'wells_projected'
rig_count                   = 'rig_count'
well_count                  = 'well_count'
footage                     = 'footage'
wells_per_rig               = 'wells_per_rig'
ln_brent_price              = 'ln_brent_price'
ln_brent_price_lagged       = 'ln_brent_price_lagged'
region_rig_constraint       = 'region_rig_constraint'
national_rig_constraint     = 'national_rig_constraint'
well_constraint             = 'well_constraint'
region_cum_rig_count        = 'region_cum_rig_count'
national_cum_rig_count      = 'national_cum_rig_count'
region_footage_constraint   = 'region_footage_constraint'
national_footage_constraint = 'national_footage_constraint'
region_cum_well_count       = 'region_cum_well_count'
national_cum_well_count     = 'national_cum_well_count'
region_cum_footage          = 'region_cum_footage'
national_cum_footage        = 'national_cum_footage'
capital_constraint          = 'capital_constraint'
cumulative_capital          = 'cumulative_capital'

#Output Variables
realized_prod_ratio         = 'realized_prod_ratio'


## Offshore variables
off_averaging_years             = 'off_averaging_years'
off_exp_success_improve_rate    = 'off_exp_success_improve_rate'
off_exp_delay_improve_rate      = 'off_exp_delay_improve_rate'
off_drill_cost_improve_rate     = 'off_drill_cost_improve_rate'
off_delay_improve_rate          = 'off_delay_improve_rate'
off_platform_cost_improve_rate  = 'off_platform_cost_improve_rate'
off_operating_cost_improve_rate = 'off_operating_cost_improve_rate'
off_oil_price_cost_base         = 'off_oil_price_cost_base'
off_drill_price_ratio           = 'off_drill_price_ratio'
off_pipeline_diameter           = 'off_pipeline_diameter'
off_wells_per_flowline          = 'off_wells_per_flowline'
off_evaluation_years            = 'off_evaluation_years'
off_platform_cost_base          = 'off_platform_cost_base'
off_drill_cost_base             = 'off_drill_cost_base'
off_base_oil_prc                = 'off_base_oil_prc'
off_base_gas_prc                = 'off_base_gas_prc'


off_mapping                     = 'off_mapping'
off_water_depth                 = 'off_water_depth'
off_drill_depth                 = 'off_drill_depth'
off_delineation_wells           = 'off_delineation_wells'
off_development_wells           = 'off_development_wells'
off_delays                      = 'off_delays'
off_platform_delays             = 'off_platform_delays'
off_exp_cost                    = 'off_exp_cost'
off_dev_cost                    = 'off_dev_cost'
off_platform_slots              = 'off_platform_slots'
off_platform_structure_type     = 'off_platform_structure_type'
off_platform_abandonment        = 'off_platform_abandonment'
off_announced_fields            = 'off_announced_fields'
off_drill_per_year              = 'off_drill_per_year'
off_platform_drill_per_year     = 'off_platform_drill_per_year'
off_field_size_classes          = 'off_field_size_classes'
off_operating_cost              = 'off_operating_cost'
off_gas_ratio_and_cond          = 'off_gas_ratio_and_cond'
off_boe_to_mcf                  = 'off_boe_to_mcf'
off_prod_fac_cost_frac          = 'off_prod_fac_cost_frac'
off_producing_fields            = 'off_producing_fields'
off_prod_profile                = 'off_prod_profile'
off_transportation              = 'off_transportation'
off_royalty                     = 'off_royalty'
off_1990_fields                 = 'off_1990_fields'
off_cumulative_nfws             = 'off_cumulative_nfws'
off_undiscovered_fields         = 'off_undiscovered_fields'
off_field_availability          = 'off_field_availability'
off_nfw_coefficients            = 'off_nfw_coefficients'
off_discovery_coefficients      = 'off_discovery_coefficients'
off_undiscovered_production     = 'off_undiscovered_production'
off_exp_success_rate            = 'off_exp_success_rate'

hsm_off_announced_fields        = 'hsm_off_announced_fields'
hsm_off_discovered_fields       = 'hsm_off_discovered_fields'
hsm_off_total_fields            = 'hsm_off_total_fields'
hsm_off_discovered_field_dist   = 'hsm_off_discovered_field_dist'
hsm_off_undiscovered_fields     = 'hsm_off_undiscovered_fields'
hsm_off_fields                  = 'hsm_off_fields'
hsm_off_fields_selected         = 'hsm_off_fields_selected'
hsm_off_cumulative_nfws         = 'hsm_off_cumulative_nfws'
hsm_off_crude_production        = 'hsm_off_crude_production'
hsm_off_natgas_production       = 'hsm_off_natgas_production'
hsm_off_adgas_production        = 'hsm_off_adgas_production'
hsm_off_nagas_production        = 'hsm_off_nagas_production'
hsm_off_wells                   = 'hsm_off_wells'

zero_year                       = 'zero_year'
final_year                      = 'final_year'
evaluation_unit                 = 'evaluation_unit'
planning_area                   = 'planning_area'
field_size_class                = 'field_size_class'
water_depth                     = 'water_depth'
water_depth_ft                  = 'water_depth_ft'
water_depth_m                   = 'water_depth_m'
drill_depth                     = 'drill_depth'
delineation_wells               = 'delineation_wells'
development_wells               = 'development_wells'
exploratory_wells               = 'exploratory_wells'
delay_years                     = 'delay_years'
well_decline_limit              = 'well_decline_limit'
max_wells                       = 'max_wells'
total_wells                     = 'total_wells'
platform_type                   = 'platform_type'
platform_slots                  = 'platform_slots'
platform_cost                   = 'platform_cost'
platform_abandonment            = 'platform_abandonment'
pipeline_diameter               = 'pipeline_diameter'
wells_per_flowline              = 'wells_per_flowline'
flowlines                       = 'flowlines'
flowline_cost                   = 'flowline_cost'
drill_per_year                  = 'drill_per_year'
completion_cost                 = 'completion cost'
min_resources_mmboe             = 'min_resources_mmboe'
max_resources_mmboe             = 'max_resources_mmboe'
mean_resources_mmboe            = 'mean_resources_mmboe'
evaluation_years                = 'evaluation_years'
gas_resources                   = 'gas_resources'
oil_resources                   = 'oil_resources'
gas_proportion                  = 'gas_proportion'
condensate_yield                = 'condensate_yield'
gas_oil_ratio                   = 'gas_oil_ratio'
oil_or_gas                      = 'oil_or_gas'
oil                             = 'oil'
gas                             = 'gas'
both                            = 'both'
fuel                            = 'fuel'
mean_resources_boe              = 'mean_resources_boe'
max_resources_boe               = 'max_resources_boe'
ramp_up_years                   = 'ramp_up_years'
prod_years                      = 'prod_years'
peak_years                      = 'peak_years'
decline_rate                    = 'decline_rate'
predecline_prod_fraction_oil    = 'predecline_prod_fraction_oil'
predecline_prod_fraction_gas    = 'predecline_prod_fraction_gas'
initial_oil_prod_rate           = 'initial_oil_prod_rate'
initial_oil_prod_rate_und       = 'initial_oil_prod_rate_und'
initial_gas_prod_rate           = 'initial_gas_prod_rate'
initial_gas_prod_rate_und       = 'initial_gas_prod_rate_und'
initial_water_prod_rate         = 'initial_water_prod_rate'
max_oil_production_rate         = 'max_oil_production_rate'
max_gas_production_rate         = 'max_gas_production_rate'
max_water_production_rate       = 'max_water_production_rate'
oil_decline_rate                = 'oil_decline_rate'
gas_decline_rate                = 'gas_decline_rate'
water_decline_rate              = 'water_decline_rate'
oil_hyper_decline_coef          = 'oil_hyper_decline_coef'
gas_hyper_decline_coef          = 'gas_hyper_decline_coef'
water_hyper_decline_coef        = 'water_hyper_decline_coef'
hyper_decline_coef              = 'hyper_decline_coef'
past_production                 = 'past_production'
year_production_start           = 'year_production_start'
discovery_year                  = 'discovery_year'
boem_assessment_year            = 'boem_assessment_year'
year_available                  = 'year_available'
lag_year                        = 'lag_year'
buffer_fraction                 = 'buffer_fraction'
available_year                  = 'available_year'
discovery_type                  = 'discovery_type'
announced                       = 'announced'
discovered                      = 'discovered'
producing                       = 'producing'
rank                            = 'rank'
discount_rate_adjustment        = 'discount_rate_adjustment'
non_condensate_production       = 'non_condensate_production'
condensate_production           = 'condensate_production'
non_associated_gas_production   = 'non_associated_gas_production'
associated_gas_production       = 'associated_gas_production'
projected_wells                 = 'projected_wells'
cum_projected_wells             = 'cum_projected_wells'
last_year_drilling              = 'last_year_drilling'

# production facilities
off_fp   = 'FP'    # 1=Fixed Platform,
off_ct   = 'CT'    # 2=Compliant Tower,
off_tlp  = 'TLP'   # 3=Tension Leg Platform,
off_fps  = 'FPS'   # 4=Floating Production System
off_spar = 'SPAR'  # 5=SPAR Platform
off_fpso = 'FPSO'  # 6=Floating Production Storage & Offloading
off_ss   = 'SS'    # 7=Subsea-system

#Drilling Rig Availability_constraint
drill_rig_constraint    = 'off_drilling_rig_availability_constraint'
drill_rig               = 'drill_rig'
water_depth_min         = 'water_depth_min'
water_depth_max         = 'water_depth_max'
num_rigs                = 'Number of Rigs (2007)'
drill_rate              = 'Drilling Days/Well'
min_rig_increment       = 'Minimum Rig Increment'
max_rig_build_rate      = 'Maximum Rig Build Rate (%)'
target_rig_util         = 'Target Rig Utilization (%)'
calculated_drilling_cap = 'Calculated Drilling Capacity (Wells/Year/Rig)'
rig_well_cap_boy        = 'rig_well_cap_boy'
rig_well_cap_eoy        = 'rig_well_cap_eoy'
rig_well_util           = 'rig_well_util'
rig_well_util_per       = 'rig_well_util_per'
rig_well_cap_inc        = 'rig_well_cap_inc'
rig_inc                 = 'rig_inc'
max_build               = 'max_build'
efficiency_scalar       = 'efficiency_scalar'
use_rank                = 'use_rank'
available_rigs          = 'available_rigs'
selected                = 'selected'
counter                 = 'counter'
item                    = 'item'

#New Field Drilling
nfw_alpha   = 'nfw_alpha'
nfw_beta    = 'nfw_beta'
lag_years   = 'lag_years'
annual_nfws = 'annual_nfws'

#NGPL Calcs
ngpl_ratio = 'ngpl_ratio'
ethane_fraction = 'ethane_fraction'
propane_fraction = 'propane_fraction'
butane_fraction = 'butane_fraction'
isobutane_fraction = 'isobutane_fraction'
natural_gasoline_fraction = 'natural_gasoline_fraction'

#Federal/non-federal
federal                 = 'federal'
not_federal             = 'not_federal'
federal_land_number     = 'federal_land_number'
offshore_region_number  = 'offshore_region_number'


###Canada Variables
can_benchmark_prices            = 'can_benchmark_prices'
can_natgas_no_export_prod       = 'can_natgas_no_export_prod'
can_natgas_resources            = 'can_natgas_resources'
can_natgas_dc_vars              = 'can_natgas_dc_vars'
can_elasticity_ad_gas           = 'can_elasticity_ad_gas'
can_natgas_baseline_prod        = 'can_natgas_baseline_prod'
can_wells                       = 'can_wells'
can_natgas_poly_eqs             = 'can_natgas_poly_eqs'


can_zero_year   = 'can_zero_year'
benchmark       = 'benchmark'
gas_type        = 'gas_type'
region          = 'region'

reference       = 'reference'
henry_hub_nom   = 'Henry Hub - 2019 US$/MMBtu'
brent_nom       = 'Brent - 2019 US$/bbl'
henry_hub_1987  = 'Henry Hub - US$/MMBtu'
brent_1987      = 'Brent - US$/bbl'
brent_int       = 'brent_int'
brent_can       = 'brent_can'
hh_cal          = 'Henry Hub - US$/MMBTU (calibrated)'

year            = 'year'
iteration       = 'iteration'
total_prod      = 'total_prod'
total_legacy    = 'total_legacy'
total_new       = 'total_new'
wells           = 'wells'
decline_curve   = 'decline_curve'
tech            = 'tech'
baseline_prod   = 'baseline_prod'
fixed_prod      = 'fixed_prod'

ad = 'associated_disolved'
na = 'non_associated'

###Alaska Variables
ak_evaluation_years     = 'ak_evaluation_years'
prod_evaluation_year    = 'prod_evaluation_year'
tech_rate               = 'tech_rate'
averaging_years         = 'averaging_years'
index                   = 'index'

ak_region_number            = 'ak_region_number'
ak_field_size_classes       = 'ak_field_size_classes'
ak_mapping                  = 'ak_mapping'
ak_exp_drill_schedule       = 'ak_exp_drill_schedule'
ak_dev_drill_schedule       = 'ak_dev_drill_schedule'
ak_facility_costs           = 'ak_facility_costs'
ak_opex                     = 'ak_opex'
ak_projects_known           = 'ak_projects_known'
ak_projects_undiscovered    = 'ak_projects_undiscovered'
hsm_ak_projects             = 'hsm_ak_projects'
hsm_ak_projects_known       = 'hsm_ak_projects_known'
hsm_ak_crude_production     = 'hsm_ak_crude_production'

min_resources_boe               = 'min_resources_boe'
exp_drill_cost_rate             = 'exp_drill_cost_rate'
dev_drill_cost_rate             = 'dev_drill_cost_rate'
kap_cost_rate                   = 'kap_cost_rate'
max_prod                        = 'max_prod'
avg_3_prod                      = 'avg_3_prod'
production_delay                = 'production_delay'
initial_oil_prod_rate_calc      = 'initial_oil_prod_rate_calc'
initial_gas_prod_rate_calc      = 'initial_gas_prod_rate_calc'
max_oil_production_rate_calc    = 'max_oil_production_rate_calc'
max_gas_production_rate_calc    = 'max_gas_production_rate_calc'
max_oil_production_rate_factor  = 'max_oil_production_rate_factor'
max_gas_production_rate_factor  = 'max_gas_production_rate_factor'
initial_oil_prod_rate_factor    = 'initial_oil_prod_rate_factor'
initial_gas_prod_rate_factor    = 'initial_gas_prod_rate_factor'
fc_decline                      = 'fc_decline'
decline_flag                    = 'decline_flag'

sev_rate_crude  = 'sev_rate_crude'
sev_rate_natgas = 'sev_rate_natgas'
exp_tang_frac   = 'exp_tang_frac'
dev_tang_frac   = 'dev_tang_frac'
kap_tang_frac   = 'kap_tang_frac'
amor_schedule   = 'amor_schedule'
deprec_schedule = 'deprec_schedule'


### NGP Submodule

natgas_prod = 'natgas_prod'
ngp_facility_input = 'ngp_facility_input'
co2_price = 'co2_price'
co2_flow = 'co2_flow'
co2_revenue = 'co2_revenue'
electricity_cost = 'electricity_cost'

facility_index = 'facility_index'
co2_price = 'co2_price'
electricity_price = 'electricity_price'

#NGP input variable names
ngp_zero_year           = 'ngp_zero_year'
ngp_final_year          = 'ngp_final_year'
ngp_amor_schedule       = 'ngp_amor_schedule'
ngp_deprec_schedule     = 'ngp_deprec_schedule'
ngp_final_45q_elig_year = 'ngp_final_45q_elig_year'
ngp_cost_tech_rate      = 'ngp_cost_tech_rate'
ngp_exp_tang_frac       = 'ngp_exp_tang_frac'
ngp_dev_tang_frac       = 'ngp_dev_tang_frac'
ngp_kap_tang_frac       = 'ngp_kap_tang_frac'
ngp_intang_amor_frac    = 'ngp_intang_amor_frac'
census_divisions        = 'census_divisions'
ngp_eval_years          = 'ngp_eval_years'
ngp_post_retrofit_cf    = 'ngp_post_retrofit_cf'
ngp_thruput_cf          = 'ngp_thruput_cf'
ngp_new_plant_cf        = 'ngp_new_plant_cf'
hr_to_yr                = 'hr_to_yr'
ngpp_retire_rate        = 'ngpp_retire_rate'
tech_rate_inv           = 'tech_rate_inv'
tech_rate_om            = 'tech_rate_om'
max_growth              = 'max_growth'
on_max_co2_prc          = 'on_max_co2_prc'

#NGP Input File Names
ngpp_input_eia_throughput = 'ngpp_input_eia_throughput'
ngpp_input_netl_throughput = 'ngpp_input_netl_throughput'
netl_purchased_power_cost = 'netl_purchased_power_cost'
netl_natural_gas_calculations = 'netl_natural_gas_calculations'
netl_purchased_power_cost = 'netl_purchased_power_cost'