rm -f SYSWHIZ.act 
rm -f BAXPMM1.dat
rm -f BAXPMM2.dat
rm -f BASPMM1.dat
rm -f BASPMM2.dat
rm -f BASEMMO.dat
rm -f BASEMMI.dat
rm -f MPSPMM.dat
rm -f MPSNRM.dat
rm -f ACTEMMI.act 
rm -f ACTPMM1.act 
rm -f ACTPMM2.act 
rm -f ACTFCES.act 
rm -f ACTFEDN.act 
rm -f COAL1CPS
rm -f EDN0SLC
