! $Header: M:/default/source/RCS/dummypp.f,v 1.4 2014/02/07 19:19:26 dsa Exp $
      SUBROUTINE GETR(IRG)
      IMPLICIT NONE
      INTEGER IRG
      RETURN
      END
      SUBROUTINE MPTIM2(ICSEC)
      IMPLICIT NONE
      INTEGER ICSEC
      write(6,*) 'Timing routine not linked in.  Use your watch. '
      return
      end
      SUBROUTINE ORCLTABS
      IMPLICIT NONE
      RETURN
      END
      SUBROUTINE LOGON (UID,PWD,DB_STRING)
      IMPLICIT NONE
      CHARACTER*3  UID
      character*8  PWD
      CHARACTER*11 DB_STRING
      RETURN
      END
      SUBROUTINE DEFNTABS
      IMPLICIT NONE
      RETURN
      END
      SUBROUTINE LOAD_ECP_GNP_DEFLATOR (UNYEAR,UPGNPD)
      IMPLICIT NONE
      INTEGER UNYEAR
      REAL*4 UPGNPD(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_Load_Segment(LOOPING, ECPLOADB, &
                            ECPLOADA, ECPLOADC, ECPLOADD, ECPLOADE, &
                            ECPLOADF, ECPLOADG, ECPLOADH, ECPLOADI, &
                            ECPLOADJ, ECPLOADK, ECPLOADL)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPLOADA(100),ECPLOADB(100),ECPLOADC(100)
      INTEGER*4 ECPLOADD(100),ECPLOADE(100)
      REAL*8 ECPLOADF(100),ECPLOADG(100),ECPLOADH(100)
      REAL*8 ECPLOADI(100),ECPLOADJ(100),ECPLOADK(100)
      REAL*8 ECPLOADL(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_Reserve_Margin(LOOPING, ECPRMARA, &
                    ECPRMARB, ECPRMARC, ECPRMARD, ECPRMARE, &
                    ECPRMARF, ECPRMARG)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPRMARA(100),ECPRMARB(100),ECPRMARC(100)
      REAL*8 ECPRMARD(100),ECPRMARE(100)
      CHARACTER*4 ECPRMARF(100)
      REAL*8 ECPRMARG(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_SO2_Allowance_Cost(LOOPING, ECPALOWB, &
                                  ECPALOWA, ECPALOWC, ECPALOWG)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPALOWA(100),ECPALOWB(100)
      CHARACTER*4 ECPALOWC(100)
      REAL*4 ECPALOWG(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_SO2_Banking(ECPBANKA, ECPBANKB, ECPBANKC)
      IMPLICIT NONE
      INTEGER*4 ECPBANKA
      CHARACTER*4 ECPBANKB
      REAL*8 ECPBANKC
      RETURN
      END
      SUBROUTINE LOAD_ECP_National_Input(LOOPING, ECPNTINA, &
                    ECPNTINB, ECPNTINC, ECPNTIND, ECPNTINE, &
                    ECPNTINF, ECPNTING, ECPNTINH, ECPNTINI, &
                    ECPNTINJ, ECPNTINK, ECPNTINL, ECPNTINM, &
                    ECPNTINN, ECPNTINQ, ECPNTINR)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPNTINA(100),ECPNTINB(100),ECPNTINC(100)
      INTEGER*4 ECPNTIND(100),ECPNTINE(100),ECPNTINF(100)
      INTEGER*4 ECPNTING(100),ECPNTINH(100)
      REAL*8 ECPNTINI(100),ECPNTINJ(100),ECPNTINK(100)
      REAL*8 ECPNTINL(100),ECPNTINM(100),ECPNTINN(100)
      REAL*8 ECPNTINQ(100),ECPNTINR(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_CONST_PROFILE (LOOPING,ECPCPROA,ECPCPROB, &
                 ECPCPROC,ECPCPROD,ECPCPROE,ECPCPROF,ECPCPROG)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPCPROA(100),ECPCPROB(100)
      REAL*8 ECPCPROC(100),ECPCPROD(100),ECPCPROE(100)
      REAL*8 ECPCPROF(100),ECPCPROG(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_DISP_CAP_PARM (LOOPING,ECPDSPPA,ECPDSPPB, &
                      ECPDSPPC,ECPDSPPD,ECPDSPPE)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPDSPPA(100)
      REAL*8 ECPDSPPB(100),ECPDSPPC(100),ECPDSPPD(100)
      REAL*8 ECPDSPPE(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_CCAP_TO_CFL (LOOPING,CCAPCFLA, CCAPCFLB, &
                                       CCAPCFLC)
      IMPLICIT NONE
      INTEGER*4 CCAPCFLA(100),CCAPCFLB(100),CCAPCFLC(100)
      INTEGER*4 LOOPING
      RETURN
      END
      SUBROUTINE LOAD_ECP_REGIONAL_INPUT(LOOPING, &
                           ECPRGINA, ECPRGINB, ECPRGINC, &
                           ECPRGIND, ECPRGINE, ECPRGINF, ECPRGING, &
                           ECPRGINH, ECPRGINI, ECPRGINJ, ECPRGINK, &
                           ECPRGINL, ECPRGINM, ECPRGINN, ECPRGINP, &
                           ECPRGINQ, ECPRGINR, ECPRGINT)
!
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPRGINA(100),ECPRGINB(100),ECPRGINC(100)
      INTEGER*4 ECPRGIND(100)
      REAL*8 ECPRGINE(100),ECPRGINF(100),ECPRGING(100)
      REAL*8 ECPRGINH(100),ECPRGINI(100),ECPRGINJ(100)
      REAL*8 ECPRGINK(100),ECPRGINL(100),ECPRGINM(100)
      REAL*8 ECPRGINN(100),ECPRGINP(100),ECPRGINQ(100)
      REAL*8 ECPRGINR(100),ECPRGINT(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_LEVELIZED_COST (LOOPING, &
                    ECPLEVA, ECPLEVB, ECPLEVC, &
                    ECPLEVD, ECPLEVE, ECPLEVF, ECPLEVG, &
                    ECPLEVH, ECPLEVI, ECPLEVJ, ECPLEVK, &
                    ECPLEVL, ECPLEVM, ECPLEVN, ECPLEVO)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPLEVA(100),ECPLEVB(100),ECPLEVC(100)
      INTEGER*4 ECPLEVD(100),ECPLEVE(100),ECPLEVF(100)
      REAL*8 ECPLEVG(100),ECPLEVH(100),ECPLEVI(100)
      REAL*8 ECPLEVJ(100),ECPLEVK(100),ECPLEVL(100)
      REAL*8 ECPLEVM(100),ECPLEVN(100),ECPLEVO(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_BLD_CHAR (LOOPING, ECPCPB11, &
             ECPCPB12, ECPCPB13, ECPCPB14, ECPCPB15, &
             ECPCPB16, ECPCPB17, ECPCPB18, ECPCPB19, &
             ECPCPB1A, ECPCPB1B, ECPCPB1D)
      IMPLICIT NONE
      INTEGER*4 LOOPING,ECPCPB11(100),ECPCPB12(100),ECPCPB13(100)
      INTEGER*4 ECPCPB14(100),ECPCPB15(100),ECPCPB1D(100)
      REAL*8 ECPCPB16(100),ECPCPB17(100),ECPCPB19(100)
      REAL*8 ECPCPB1A(100),ECPCPB1B(100)
      CHARACTER*25 ECPCPB18(100)
      RETURN
      END
      SUBROUTINE LOAD_ECP_Purchased_Capacity(ECPURCH1, &
                 ECPURCH2, ECPURCH3,ECPURCH4, ECPURCH5, ECPURCH6, &
                 ECPURCH7, ECPURCH8)
      IMPLICIT NONE
      INTEGER*4 ECPURCH1,ECPURCH2
      REAL*4 ECPURCH3,ECPURCH4,ECPURCH5
      REAL*4 ECPURCH6,ECPURCH7
      REAL*8 ECPURCH8
      RETURN
      END
      SUBROUTINE LOAD_ecp_Nom_Fuel_Cost (LOOPING, ECPPRC1A, &
                     ECPPRC1B, ECPPRC1C, ECPPRC1D,ECPPRC1E)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 ECPPRC1A(100),ECPPRC1B(100)
      INTEGER*4 ECPPRC1C(100),ECPPRC1D(100)
      REAL*8 ECPPRC1E(100)
      RETURN
      END
      SUBROUTINE LOAD_ecp_Fuel_Costs_Lump (LOOPING,ECPPRC2A, &
                            ECPPRC2B,ECPPRC2C, ECPPRC2D, ECPPRC2E)
      IMPLICIT NONE
      INTEGER*4 ECPPRC2A(100),ECPPRC2B(100)
      INTEGER*4 ECPPRC2C(100),ECPPRC2D(100)
      REAL*8 ECPPRC2E(100)
      INTEGER LOOPING
      RETURN
      END
      SUBROUTINE LOAD_ecp_Fuel_SO2_Content( ECP_SO2A, &
                        ECP_SO2B, ECP_SO2C, ECP_SO2D)
      IMPLICIT NONE
      INTEGER*4 ECP_SO2A(13),ECP_SO2B(13)
      INTEGER*4 ECP_SO2C(13)
      REAL*8 ECP_SO2D(13)
      RETURN
      END
      SUBROUTINE  LOAD_ecp_Utilization(LOOPING, ECPDRATA, ECPDRATB, &
                            ECPDRATC, &
                            ECPDRATD, ECPDRATE, ECPDRATF, ECPDRATG, &
                            ECPDRATH, ECPDRATI, ECPDRATJ, ECPDRATK, &
                            ECPDRATL, ECPDRATM, ECPDRATN, ECPDRATP)
      IMPLICIT NONE
      INTEGER*4 ECPDRATA(100),ECPDRATB(100),ECPDRATC(100)
      INTEGER*4 ECPDRATD(100)
      REAL*8 ECPDRATE(100),ECPDRATF(100),ECPDRATG(100)
      REAL*8 ECPDRATH(100),ECPDRATI(100),ECPDRATJ(100)
      REAL*8 ECPDRATK(100),ECPDRATL(100),ECPDRATM(100)
      REAL*8 ECPDRATN(100),ECPDRATP(100)
      INTEGER LOOPING
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSPTOV(LOOPING, EFDDOSPTOVA, EFDDOSPTOVB, &
        EFDDOSPTOVB1,EFDDOSPTOVC, EFDDOSPTOVD, EFDDOSPTOVE, EFDDOSPTOVF)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDOSPTOVA(100), EFDDOSPTOVB(100), EFDDOSPTOVC(100), &
                EFDDOSPTOVD(100), EFDDOSPTOVE(100), EFDDOSPTOVB1(100)
      REAL*4 EFDDOSPTOVF(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSPTO (LOOPING, EFDDOSPTOA, EFDDOSPTOB, &
            EFDDOSPTOB1, EFDDOSPTOC, EFDDOSPTOD, EFDDOSPTOE, EFDDOSPTOF, &
            EFDDOSPTOG, EFDDOSPTOH, EFDDOSPTOI)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDOSPTOA(100), EFDDOSPTOB(100), EFDDOSPTOC(100), &
                EFDDOSPTOD(100), EFDDOSPTOB1(100)
      REAL*4 EFDDOSPTOE(100), EFDDOSPTOF(100), EFDDOSPTOG(100), &
             EFDDOSPTOH(100), EFDDOSPTOI(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSPTS (LOOPING, EFDDOSPTSA, EFDDOSPTSB, &
                   EFDDOSPTSB1, EFDDOSPTSC, EFDDOSPTSD, EFDDOSPTSE, &
                   EFDDOSPTSF, EFDDOSPTSG)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDOSPTSA(1500), EFDDOSPTSB(1500), EFDDOSPTSC(1500), &
                EFDDOSPTSD(1500), EFDDOSPTSB1(1500)
      REAL*4 EFDDOSPTSE(1500), EFDDOSPTSF(1500), EFDDOSPTSG(1500)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSPTF (LOOPING, EFDDOSPTFA, EFDDOSPTFB, &
                   EFDDOSPTFB1, EFDDOSPTFC, EFDDOSPTFD, EFDDOSPTFE, &
                   EFDDOSPTFF, EFDDOSPTFG)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDOSPTFA(100), EFDDOSPTFB(100), EFDDOSPTFC(100), &
                EFDDOSPTFD(100), EFDDOSPTFE(100), EFDDOSPTFB1(100)
      REAL*4 EFDDOSPTFF(100), EFDDOSPTFG(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSPT (LOOPING, EFDDOSPTA, EFDDOSPTB, &
               EFDDOSPTB1, EFDDOSPTC, EFDDOSPTD, EFDDOSPTE, EFDDOSPTF, &
               EFDDOSPTG, EFDDOSPTH, EFDDOSPTI)
      IMPLICIT NONE
      INTEGER*4 LOOPING, EFDDOSPTB1(100)
      INTEGER*4 EFDDOSPTA(100), EFDDOSPTB(100), EFDDOSPTC(100)
      REAL*4 EFDDOSPTD(100), EFDDOSPTF(100), EFDDOSPTG(100), &
             EFDDOSPTH(100), EFDDOSPTI(100)
      REAL*8 EFDDOSPTE(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSFT (LOOPING, EFDDOSFTA, EFDDOSFTB, &
        EFDDOSFTB1, EFDDOSFTC, EFDDOSFTD, EFDDOSFTE, EFDDOSFTF, &
                    EFDDOSFTG, EFDDOSFTH, EFDDOSFTI, EFDDOSFTJ, &
                    EFDDOSFTK, EFDDOSFTL)
      IMPLICIT NONE
      INTEGER*4 LOOPING, EFDDOSFTB1(100)
      INTEGER*4 EFDDOSFTA(100), EFDDOSFTB(100), EFDDOSFTC(100)
      REAL*4 EFDDOSFTD(100), EFDDOSFTE(100), EFDDOSFTF(100), &
             EFDDOSFTG(100), EFDDOSFTH(100), EFDDOSFTI(100), &
             EFDDOSFTJ(100), EFDDOSFTK(100), EFDDOSFTL(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOSFTO (LOOPING, EFDDOSFTOA, EFDDOSFTOB, &
        EFDDOSFTOB1,EFDDOSFTOC, EFDDOSFTOD, EFDDOSFTOE, EFDDOSFTOF)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDOSFTOA(100), EFDDOSFTOB(100), EFDDOSFTOC(100), &
                EFDDOSFTOD(100), EFDDOSFTOB1(100)
      REAL*4  EFDDOSFTOE(100), EFDDOSFTOF(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DSO2A (LOOPING, EFDDSO2AA, EFDDSO2AB, &
         EFDDSO2AB1,EFDDSO2AC, EFDDSO2AD, EFDDSO2AE, EFDDSO2AF)
      IMPLICIT NONE
      INTEGER*4 LOOPING,EFDDSO2AB1(100)
      INTEGER*4 EFDDSO2AA(100), EFDDSO2AB(100), EFDDSO2AC(100)
      REAL*4  EFDDSO2AD(100), EFDDSO2AE(100), EFDDSO2AF(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DSEASINFO (LOOPING, EFDDSEASINFOA, &
                    EFDDSEASINFOB, EFDDSEASINFOC, EFDDSEASINFOD, &
                    EFDDSEASINFOE, EFDDSEASINFOF, EFDDSEASINFOG, &
                    EFDDSEASINFOH, EFDDSEASINFOI)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDSEASINFOA(100), EFDDSEASINFOB(100), &
                EFDDSEASINFOC(100), EFDDSEASINFOD(100)
      REAL*8  EFDDSEASINFOE(100), EFDDSEASINFOF(100), &
              EFDDSEASINFOG(100)
      REAL*4  EFDDSEASINFOH(100), EFDDSEASINFOI(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DLOAD (LOOPING, EFDDLOADA, &
                    EFDDLOADB, EFDDLOADC, EFDDLOADD, &
                    EFDDLOADE, EFDDLOADF, EFDDLOADG, &
                    EFDDLOADH, EFDDLOADI, EFDDLOADJ, &
                    EFDDLOADK, EFDDLOADL)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDLOADA(1500), EFDDLOADB(1500), EFDDLOADC(1500), &
                EFDDLOADD(1500), EFDDLOADE(1500), EFDDLOADF(1500), &
                EFDDLOADG(1500)
      REAL*8  EFDDLOADH(1500), EFDDLOADI(1500), EFDDLOADJ(1500), &
              EFDDLOADK(1500), EFDDLOADL(1500)
      RETURN
      END
      SUBROUTINE LOAD_efd_DTRADE (LOOPING, EFDDTRADEA, &
                    EFDDTRADEB, EFDDTRADEB1,EFDDTRADEC, EFDDTRADED, &
                    EFDDTRADEE, EFDDTRADEF, EFDDTRADEG, &
                    EFDDTRADEH, EFDDTRADEI, EFDDTRADEJ, &
                    EFDDTRADEK, EFDDTRADEL, EFDDTRADEM)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDTRADEA(100), EFDDTRADEB(100), EFDDTRADEB1(100)
      REAL*4 EFDDTRADEC(100), EFDDTRADED(100), EFDDTRADEE(100), &
             EFDDTRADEF(100), EFDDTRADEG(100), EFDDTRADEH(100), &
             EFDDTRADEI(100), EFDDTRADEJ(100), &
             EFDDTRADEK(100), EFDDTRADEL(100), EFDDTRADEM(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DEMIS (LOOPING, EFDDEMISA, &
                    EFDDEMISB, EFDDEMISB1, EFDDEMISC, EFDDEMISD, &
                    EFDDEMISE, EFDDEMISF, EFDDEMISG, &
                    EFDDEMISH, EFDDEMISI, EFDDEMISJ)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDEMISA(100), EFDDEMISB(100), EFDDEMISB1(100)
      REAL*4 EFDDEMISC(100), EFDDEMISD(100), EFDDEMISE(100), &
             EFDDEMISF(100), EFDDEMISG(100), EFDDEMISH(100), &
             EFDDEMISI(100), EFDDEMISJ(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DOS (LOOPING, EFDDOSA, &
                    EFDDOSB, EFDDOSB1,EFDDOSC, EFDDOSD, &
                    EFDDOSE, EFDDOSF, EFDDOSG, &
                    EFDDOSH, EFDDOSI, EFDDOSJ, &
                    EFDDOSK, EFDDOSL, EFDDOSM, &
                    EFDDOSN, EFDDOSO, EFDDOSP)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDOSA(100), EFDDOSB(100), EFDDOSB1(100)
      REAL*4 EFDDOSC(100), EFDDOSD(100), EFDDOSE(100), &
             EFDDOSF(100), EFDDOSG(100), EFDDOSH(100), &
             EFDDOSI(100), EFDDOSJ(100), EFDDOSK(100), &
             EFDDOSL(100), EFDDOSM(100), EFDDOSN(100), &
             EFDDOSO(100), EFDDOSP(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DPLT (LOOPING,  EFDDPLTA, &
                EFDDPLTB,  EFDDPLTB1, EFDDPLTC,  EFDDPLTNN, EFDDPLTD, &
                EFDDPLTE,  EFDDPLTF,  EFDDPLTG, EFDDPLTH, &
                EFDDPLTEE, EFDDPLTCC,  EFDDPLTHH, &
                EFDDPLTI,  EFDDPLTJ, &
                EFDDPLTK,  EFDDPLTL,  EFDDPLTM, &
                EFDDPLTN,  EFDDPLTO,  EFDDPLTP, &
                EFDDPLTQ,  EFDDPLTR,  EFDDPLTS, &
                EFDDPLTT,  EFDDPLTU,  EFDDPLTV, &
                EFDDPLTW,  EFDDPLTX,  EFDDPLTY, &
                EFDDPLTZ,  EFDDPLTAA, EFDDPLTBB, &
                EFDDPLTDD,  EFDDPLTFF, EFDDPLTGG, &
                EFDDPLTII, EFDDPLTJJ, EFDDPLTKK, &
                EFDDPLTLL, EFDDPLTMM, &
                EFDDPLTOO, EFDDPLTPP, EFDDPLTQQ, &
                EFDDPLTRR, EFDDPLTSS, EFDDPLTTT, &
                EFDDPLTUU, EFDDPLTVV, EFDDPLTWW, &
                EFDDPLTXX, EFDDPLTYY, EFDDPLTZZ, &
                EFDDPLT1, EFDDPLT2, EFDDPLT3, &
                EFDDPLT4, EFDDPLT5, EFDDPLT6, &
                EFDDPLT7, EFDDPLT8, EFDDPLT9)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDPLTA(1500), EFDDPLTB(1500), EFDDPLTC(1500), &
                EFDDPLTD(1500), EFDDPLTE(1500), EFDDPLTF(1500), &
                EFDDPLTG(1500), EFDDPLTH(1500), EFDDPLTB1(1500)
      REAL*8 EFDDPLTI(1500), EFDDPLTJ(1500), EFDDPLTK(1500), &
             EFDDPLTL(1500), EFDDPLTM(1500), EFDDPLTN(1500), &
             EFDDPLTO(1500), EFDDPLTP(1500), EFDDPLTQ(1500), &
             EFDDPLTR(1500), EFDDPLTS(1500), EFDDPLTT(1500), &
             EFDDPLTU(1500), EFDDPLTOO(1500), EFDDPLTPP(1500), &
             EFDDPLTQQ(1500), EFDDPLTRR(1500), EFDDPLTSS(1500), &
             EFDDPLTTT(1500), EFDDPLTUU(1500), EFDDPLTVV(1500), &
             EFDDPLTWW(1500), EFDDPLTXX(1500), EFDDPLTYY(1500), &
             EFDDPLTZZ(1500), EFDDPLT1(1500), EFDDPLT2(1500), &
             EFDDPLT3(1500), EFDDPLT4(1500), EFDDPLT5(1500), &
             EFDDPLT6(1500)
      INTEGER*4 EFDDPLTV(1500),  EFDDPLTW(1500), EFDDPLTX(1500), &
                EFDDPLTY(1500),  EFDDPLTZ(1500), EFDDPLTAA(1500), &
                EFDDPLTBB(1500), EFDDPLTCC(1500), EFDDPLTNN(1500), &
                EFDDPLT7(1500),  EFDDPLT8(1500),  EFDDPLT9(1500)
      CHARACTER*2 EFDDPLTDD(1500)
      INTEGER*4 EFDDPLTEE(1500), EFDDPLTFF(1500), EFDDPLTGG(1500), &
                EFDDPLTHH(1500)
      CHARACTER*2 EFDDPLTII(1500), EFDDPLTJJ(1500)
      CHARACTER*1 EFDDPLTKK(1500)
      INTEGER*4 EFDDPLTLL(1500), EFDDPLTMM(1500)
      RETURN
      END
      SUBROUTINE LOAD_efd_DBALRO (LOOPING,  EFDDBALROA, &
                    EFDDBALROB,  EFDDBALROC,  EFDDBALROD, &
                    EFDDBALROE,  EFDDBALROF,  EFDDBALROG)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDBALROA(100), EFDDBALROB(100), EFDDBALROC(100), &
                EFDDBALROD(100), EFDDBALROE(100)
      REAL*8 EFDDBALROF(100), EFDDBALROG(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DBALR (LOOPING,  EFDDBALRA, &
                     EFDDBALRB, EFDDBALRC, EFDDBALRD, &
                     EFDDBALRE, EFDDBALRF, EFDDBALRG, &
                     EFDDBALRH, EFDDBALRI, EFDDBALRJ, &
                     EFDDBALRK, EFDDBALRL, EFDDBALRM, &
                     EFDDBALRN, EFDDBALRO, EFDDBALRP, &
                     EFDDBALRQ, EFDDBALRR, EFDDBALRS, &
                     EFDDBALRT)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDBALRA(100), EFDDBALRB(100), EFDDBALRC(100), &
                EFDDBALRD(100)
      REAL*8 EFDDBALRE(100), EFDDBALRF(100), EFDDBALRG(100), &
             EFDDBALRH(100), EFDDBALRI(100), EFDDBALRJ(100)
      REAL EFDDBALRK(100), EFDDBALRL(100), EFDDBALRM(100), &
           EFDDBALRN(100), EFDDBALRO(100), EFDDBALRP(100), &
           EFDDBALRQ(100), EFDDBALRR(100), EFDDBALRS(100), &
           EFDDBALRT(100)
      RETURN
      END
      SUBROUTINE LOAD_efd_DPGDT (LOOPING,  EFDDPGDTA, &
           EFDDPGDTA1, EFDDPGDTB,  EFDDPGDTB1,  EFDDPGDTC, &
           EFDDPGDTD, EFDDPGDTE,  EFDDPGDTF,  EFDDPGDTF1, &
           EFDDPGDTG, EFDDPGDTN, EFDDPGDTH,  EFDDPGDTI,  EFDDPGDTJ, &
                    EFDDPGDTK,  EFDDPGDTL,  EFDDPGDTM,   EFDDPGDTP, &
                    EFDDPGDTQ,  EFDDPGDTR,  EFDDPGDTS, &
                    EFDDPGDTT,  EFDDPGDTU,  EFDDPGDTV, &
                    EFDDPGDTW,  EFDDPGDTX,  EFDDPGDTY, &
                    EFDDPGDTZ,  EFDDPGDTAA, EFDDPGDTBB)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDPGDTA(1500), EFDDPGDTA1(1500), EFDDPGDTB(1500), &
                EFDDPGDTB1(1500), EFDDPGDTF1(1500)
      INTEGER*4 EFDDPGDTC(1500), EFDDPGDTD(1500), EFDDPGDTE(1500), &
                EFDDPGDTF(1500), EFDDPGDTG(1500), EFDDPGDTH(1500), &
                EFDDPGDTI(1500), EFDDPGDTJ(1500), EFDDPGDTK(1500), &
                EFDDPGDTL(1500), EFDDPGDTM(1500), EFDDPGDTN(1500)
      REAL*4 EFDDPGDTP(1500)
      INTEGER*4 EFDDPGDTQ(1500), EFDDPGDTR(1500), EFDDPGDTS(1500)
      REAL*4 EFDDPGDTT(1500), EFDDPGDTU(1500)
      INTEGER*4 EFDDPGDTV(1500)
      REAL*4 EFDDPGDTW(1500), EFDDPGDTX(1500), EFDDPGDTY(1500)
      REAL*4 EFDDPGDTZ(1500), EFDDPGDTAA(1500),EFDDPGDTBB(1500)
      RETURN
      END
      SUBROUTINE LOAD_efd_DPGFLRG (LOOPING,  EFDDPGFLRGA, &
                   EFDDPGFLRGB, EFDDPGFLRGC, EFDDPGFLRGD, &
                   EFDDPGFLRGE, EFDDPGFLRGF, EFDDPGFLRGG, &
                   EFDDPGFLRGH, EFDDPGFLRGI, EFDDPGFLRGJ, &
                   EFDDPGFLRGK, EFDDPGFLRGL, EFDDPGFLRGM, &
                   EFDDPGFLRGN)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDPGFLRGA(1500), EFDDPGFLRGB(1500), &
                EFDDPGFLRGC(1500), EFDDPGFLRGD(1500), &
                EFDDPGFLRGH(1500)
      REAL*4 EFDDPGFLRGE(1500), EFDDPGFLRGF(1500), EFDDPGFLRGG(1500), &
             EFDDPGFLRGI(1500), EFDDPGFLRGJ(1500), EFDDPGFLRGK(1500), &
             EFDDPGFLRGL(1500), EFDDPGFLRGM(1500), EFDDPGFLRGN(1500)
      RETURN
      END
      SUBROUTINE LOAD_efd_DPGSEAS (LOOPING,  EFDDPGSEAA, &
                   EFDDPGSEAB, EFDDPGSEAC, EFDDPGSEAD, &
                   EFDDPGSEAE, EFDDPGSEAF, EFDDPGSEAG, &
                   EFDDPGSEAH, EFDDPGSEAI, EFDDPGSEAJ, &
                   EFDDPGSEAK)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      INTEGER*4 EFDDPGSEAA(1500), EFDDPGSEAB(1500), &
                EFDDPGSEAC(1500), EFDDPGSEAD(1500)
      REAL*4 EFDDPGSEAE(1500), EFDDPGSEAF(1500), EFDDPGSEAG(1500), &
             EFDDPGSEAI(1500), EFDDPGSEAJ(1500), EFDDPGSEAK(1500), &
             EFDDPGSEAH(1500)
      RETURN
      END
      SUBROUTINE LOAD_EFP (DYNSTM, NUMCOLS, LOOPING, COLVALS)
      IMPLICIT NONE
      INTEGER*4 LOOPING
      CHARACTER*150 DYNSTM
      INTEGER NUMCOLS
      REAL*4 COLVALS(20,1000)
      RETURN
      END
      subroutine sqlerr
      stop
      end
