!-*- f90 -*-
!******************************************************************
!*    Subroutine AVEPAS
!*
!*    Averages prices across sector and region
!******************************************************************
      SUBROUTINE AVEPAS
      IMPLICIT NONE

      include 'parametr'
      include 'qblk'
      include 'mpblk'
      include 'ncntrl'
      include 'cdsparms'
      include 'coalout'
      include 'indout'
      include 'ponroad'
      include 'qonroad'
      include 'ngtdmout'

      INTEGER IY          ! INDEX FOR YEAR
      INTEGER IC          ! INDEX FOR CENSUS REGION
      INTEGER IV,IP,IPRC  ! INDICES FOR PRICE VARIABLE
      INTEGER IQ,IQTY     ! INDEX FOR QUANTITY VARIABLE
      INTEGER NUMPAS,IR
      EXTERNAL NUMP_AS
      INTEGER NUMP_AS
      EXTERNAL PQMATCH
      INTEGER PQMATCH

      IY = CURIYR
!WRITE(*,*)"start AVEPAS()"
!WRITE(*,*)"AVEPAS(), IY=CURIYR,IY=",IY
!WRITE(*,*)"AVEPAS(), MNUMCR=",MNUMCR
!WRITE(*,*)"AVEPAS(), MNUMP=",MNUMP 
! temporarily set PCLGAS here until it is set for real somewhere
      PCLGAS(:,IY) = PCLEL(:,IY)

      INQLGPF(MNUMCR,CURIYR) = 0.0
      PLGINPF(MNUMCR,CURIYR) = 0.0
      QCLGAS(MNUMCR,CURIYR) = 0.0
      PCLGAS(MNUMCR,CURIYR) = 0.0
      PDSTRHWY(MNUMCR,CURIYR) = 0.0
      QGFTRFV(MNUMCR,CURIYR) = 0.0
      QGFTRPV(MNUMCR,CURIYR) = 0.0
      QGLTRFV(MNUMCR,CURIYR) = 0.0
      QGLTRPV(MNUMCR,CURIYR) = 0.0
      QGFTRRAIL(:,MNUMCR,CURIYR) = 0.0
      QGLTRRAIL(:,MNUMCR,CURIYR) = 0.0
      QGFTRSHIP(:,MNUMCR,CURIYR) = 0.0
      QGLTRSHIP(:,MNUMCR,CURIYR) = 0.0
      PGFTRFV(MNUMCR,CURIYR) = 0.0
      PGFTRPV(MNUMCR,CURIYR) = 0.0
      PGLTRFV(MNUMCR,CURIYR) = 0.0
      PGLTRPV(MNUMCR,CURIYR) = 0.0
      PGFTRRAIL(:,MNUMCR,CURIYR) = 0.0
      PGLTRRAIL(:,MNUMCR,CURIYR) = 0.0
      PGFTRSHIP(:,MNUMCR,CURIYR) = 0.0
      PGLTRSHIP(:,MNUMCR,CURIYR) = 0.0
      DO IC=1,MNUMCR-2
         INQLGPF(MNUMCR,CURIYR) = INQLGPF(MNUMCR,CURIYR) + INQLGPF(IC,CURIYR)
         PLGINPF(MNUMCR,CURIYR) = PLGINPF(MNUMCR,CURIYR) + PLGINPF(IC,CURIYR) * INQLGPF(IC,CURIYR)
         QCLGAS(MNUMCR,CURIYR) = QCLGAS(MNUMCR,CURIYR) + QCLGAS(IC,CURIYR)
         PCLGAS(MNUMCR,CURIYR) = PCLGAS(MNUMCR,CURIYR) + QCLGAS(IC,CURIYR) * PCLGAS(IC,CURIYR)
         PDSTRHWY(MNUMCR,CURIYR) = PDSTRHWY(MNUMCR,CURIYR) + QDSTRHWY(IC,CURIYR) * PDSTRHWY(IC,CURIYR)
         QGFTRFV(MNUMCR,CURIYR) = QGFTRFV(MNUMCR,CURIYR) + QGFTRFV(IC,CURIYR)
         QGFTRPV(MNUMCR,CURIYR) = QGFTRPV(MNUMCR,CURIYR) + QGFTRPV(IC,CURIYR)
         QGLTRFV(MNUMCR,CURIYR) = QGLTRFV(MNUMCR,CURIYR) + QGLTRFV(IC,CURIYR)
         QGLTRPV(MNUMCR,CURIYR) = QGLTRPV(MNUMCR,CURIYR) + QGLTRPV(IC,CURIYR)
         QGFTRRAIL(1,MNUMCR,CURIYR) = QGFTRRAIL(1,MNUMCR,CURIYR) + QGFTRRAIL(1,IC,CURIYR)
         QGFTRRAIL(2,MNUMCR,CURIYR) = QGFTRRAIL(2,MNUMCR,CURIYR) + QGFTRRAIL(2,IC,CURIYR)
         QGFTRRAIL(3,MNUMCR,CURIYR) = QGFTRRAIL(3,MNUMCR,CURIYR) + QGFTRRAIL(3,IC,CURIYR)
         QGFTRRAIL(4,MNUMCR,CURIYR) = QGFTRRAIL(4,MNUMCR,CURIYR) + QGFTRRAIL(4,IC,CURIYR)
         QGLTRRAIL(1,MNUMCR,CURIYR) = QGLTRRAIL(1,MNUMCR,CURIYR) + QGLTRRAIL(1,IC,CURIYR)
         QGLTRRAIL(2,MNUMCR,CURIYR) = QGLTRRAIL(2,MNUMCR,CURIYR) + QGLTRRAIL(2,IC,CURIYR)
         QGLTRRAIL(3,MNUMCR,CURIYR) = QGLTRRAIL(3,MNUMCR,CURIYR) + QGLTRRAIL(3,IC,CURIYR)
         QGLTRRAIL(4,MNUMCR,CURIYR) = QGLTRRAIL(4,MNUMCR,CURIYR) + QGLTRRAIL(4,IC,CURIYR)
         QGFTRSHIP(1,MNUMCR,CURIYR) = QGFTRSHIP(1,MNUMCR,CURIYR) + QGFTRSHIP(1,IC,CURIYR)
         QGFTRSHIP(2,MNUMCR,CURIYR) = QGFTRSHIP(2,MNUMCR,CURIYR) + QGFTRSHIP(2,IC,CURIYR)
         QGFTRSHIP(3,MNUMCR,CURIYR) = QGFTRSHIP(3,MNUMCR,CURIYR) + QGFTRSHIP(3,IC,CURIYR)
         QGLTRSHIP(1,MNUMCR,CURIYR) = QGLTRSHIP(1,MNUMCR,CURIYR) + QGLTRSHIP(1,IC,CURIYR)
         QGLTRSHIP(2,MNUMCR,CURIYR) = QGLTRSHIP(2,MNUMCR,CURIYR) + QGLTRSHIP(2,IC,CURIYR)
         QGLTRSHIP(3,MNUMCR,CURIYR) = QGLTRSHIP(3,MNUMCR,CURIYR) + QGLTRSHIP(3,IC,CURIYR)
         PGFTRFV(MNUMCR,CURIYR) = PGFTRFV(MNUMCR,CURIYR) + PGFTRFV(IC,CURIYR) * QGFTRFV(IC,CURIYR)
         PGFTRPV(MNUMCR,CURIYR) = PGFTRPV(MNUMCR,CURIYR) + PGFTRPV(IC,CURIYR) * QGFTRPV(IC,CURIYR)
         PGLTRFV(MNUMCR,CURIYR) = PGLTRFV(MNUMCR,CURIYR) + PGLTRFV(IC,CURIYR) * QGLTRFV(IC,CURIYR)
         PGLTRPV(MNUMCR,CURIYR) = PGLTRPV(MNUMCR,CURIYR) + PGLTRPV(IC,CURIYR) * QGLTRPV(IC,CURIYR)
         PGFTRRAIL(1,MNUMCR,CURIYR) = PGFTRRAIL(1,MNUMCR,CURIYR) + PGFTRRAIL(1,IC,CURIYR) * QGFTRRAIL(1,IC,CURIYR)
         PGFTRRAIL(2,MNUMCR,CURIYR) = PGFTRRAIL(2,MNUMCR,CURIYR) + PGFTRRAIL(2,IC,CURIYR) * QGFTRRAIL(2,IC,CURIYR)
         PGFTRRAIL(3,MNUMCR,CURIYR) = PGFTRRAIL(3,MNUMCR,CURIYR) + PGFTRRAIL(3,IC,CURIYR) * QGFTRRAIL(3,IC,CURIYR)
         PGFTRRAIL(4,MNUMCR,CURIYR) = PGFTRRAIL(4,MNUMCR,CURIYR) + PGFTRRAIL(4,IC,CURIYR) * QGFTRRAIL(4,IC,CURIYR)
         PGLTRRAIL(1,MNUMCR,CURIYR) = PGLTRRAIL(1,MNUMCR,CURIYR) + PGLTRRAIL(1,IC,CURIYR) * QGLTRRAIL(1,IC,CURIYR)
         PGLTRRAIL(2,MNUMCR,CURIYR) = PGLTRRAIL(2,MNUMCR,CURIYR) + PGLTRRAIL(2,IC,CURIYR) * QGLTRRAIL(2,IC,CURIYR)
         PGLTRRAIL(3,MNUMCR,CURIYR) = PGLTRRAIL(3,MNUMCR,CURIYR) + PGLTRRAIL(3,IC,CURIYR) * QGLTRRAIL(3,IC,CURIYR)
         PGLTRRAIL(4,MNUMCR,CURIYR) = PGLTRRAIL(4,MNUMCR,CURIYR) + PGLTRRAIL(4,IC,CURIYR) * QGLTRRAIL(4,IC,CURIYR)
         PGFTRSHIP(1,MNUMCR,CURIYR) = PGFTRSHIP(1,MNUMCR,CURIYR) + PGFTRSHIP(1,IC,CURIYR) * QGFTRSHIP(1,IC,CURIYR)
         PGFTRSHIP(2,MNUMCR,CURIYR) = PGFTRSHIP(2,MNUMCR,CURIYR) + PGFTRSHIP(2,IC,CURIYR) * QGFTRSHIP(2,IC,CURIYR)
         PGFTRSHIP(3,MNUMCR,CURIYR) = PGFTRSHIP(3,MNUMCR,CURIYR) + PGFTRSHIP(3,IC,CURIYR) * QGFTRSHIP(3,IC,CURIYR)
         PGLTRSHIP(1,MNUMCR,CURIYR) = PGLTRSHIP(1,MNUMCR,CURIYR) + PGLTRSHIP(1,IC,CURIYR) * QGLTRSHIP(1,IC,CURIYR)
         PGLTRSHIP(2,MNUMCR,CURIYR) = PGLTRSHIP(2,MNUMCR,CURIYR) + PGLTRSHIP(2,IC,CURIYR) * QGLTRSHIP(2,IC,CURIYR)
         PGLTRSHIP(3,MNUMCR,CURIYR) = PGLTRSHIP(3,MNUMCR,CURIYR) + PGLTRSHIP(3,IC,CURIYR) * QGLTRSHIP(3,IC,CURIYR)
      ENDDO
      IF (INQLGPF(MNUMCR,CURIYR) .NE. 0.0) THEN
        PLGINPF(MNUMCR,CURIYR) = PLGINPF(MNUMCR,CURIYR) / INQLGPF(MNUMCR,CURIYR)
      ELSE
        PLGINPF(MNUMCR,CURIYR) = sum(PLGINPF(1:9,CURIYR)) / 9.
      ENDIF
      IF (QCLGAS(MNUMCR,CURIYR) .NE. 0.0) THEN
        PCLGAS(MNUMCR,CURIYR) = PCLGAS(MNUMCR,CURIYR) / QCLGAS(MNUMCR,CURIYR)
      ELSE
        PCLGAS(MNUMCR,CURIYR) = sum(PCLGAS(1:9,CURIYR)) / 9.
      ENDIF
      IF (QDSTRHWY(MNUMCR,CURIYR) .NE. 0.0) THEN
        PDSTRHWY(MNUMCR,CURIYR) = PDSTRHWY(MNUMCR,CURIYR) / QDSTRHWY(MNUMCR,CURIYR)
      ELSE
        PDSTRHWY(MNUMCR,CURIYR) = sum(PDSTRHWY(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRFV(MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRFV(MNUMCR,CURIYR) = PGFTRFV(MNUMCR,CURIYR) / QGFTRFV(MNUMCR,CURIYR)
      ELSE
        PGFTRFV(MNUMCR,CURIYR) = sum(PGFTRFV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRPV(MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRPV(MNUMCR,CURIYR) = PGFTRPV(MNUMCR,CURIYR) / QGFTRPV(MNUMCR,CURIYR)
      ELSE
        PGFTRPV(MNUMCR,CURIYR) = sum(PGFTRPV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRFV(MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRFV(MNUMCR,CURIYR) = PGLTRFV(MNUMCR,CURIYR) / QGLTRFV(MNUMCR,CURIYR)
      ELSE
        PGLTRFV(MNUMCR,CURIYR) = sum(PGLTRFV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRPV(MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRPV(MNUMCR,CURIYR) = PGLTRPV(MNUMCR,CURIYR) / QGLTRPV(MNUMCR,CURIYR)
      ELSE
        PGLTRPV(MNUMCR,CURIYR) = sum(PGLTRPV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRRAIL(1,MNUMCR,CURIYR) = PGFTRRAIL(1,MNUMCR,CURIYR) / QGFTRRAIL(1,MNUMCR,CURIYR)
      ELSE
        PGFTRRAIL(1,MNUMCR,CURIYR) = sum(PGFTRRAIL(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRRAIL(2,MNUMCR,CURIYR) = PGFTRRAIL(2,MNUMCR,CURIYR) / QGFTRRAIL(2,MNUMCR,CURIYR)
      ELSE
        PGFTRRAIL(2,MNUMCR,CURIYR) = sum(PGFTRRAIL(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRRAIL(3,MNUMCR,CURIYR) = PGFTRRAIL(3,MNUMCR,CURIYR) / QGFTRRAIL(3,MNUMCR,CURIYR)
      ELSE
        PGFTRRAIL(3,MNUMCR,CURIYR) = sum(PGFTRRAIL(3,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(4,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRRAIL(4,MNUMCR,CURIYR) = PGFTRRAIL(4,MNUMCR,CURIYR) / QGFTRRAIL(4,MNUMCR,CURIYR)
      ELSE
        PGFTRRAIL(4,MNUMCR,CURIYR) = sum(PGFTRRAIL(4,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRRAIL(1,MNUMCR,CURIYR) = PGLTRRAIL(1,MNUMCR,CURIYR) / QGLTRRAIL(1,MNUMCR,CURIYR)
      ELSE
        PGLTRRAIL(1,MNUMCR,CURIYR) = sum(PGLTRRAIL(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRRAIL(2,MNUMCR,CURIYR) = PGLTRRAIL(2,MNUMCR,CURIYR) / QGLTRRAIL(2,MNUMCR,CURIYR)
      ELSE
        PGLTRRAIL(2,MNUMCR,CURIYR) = sum(PGLTRRAIL(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRRAIL(3,MNUMCR,CURIYR) = PGLTRRAIL(3,MNUMCR,CURIYR) / QGLTRRAIL(3,MNUMCR,CURIYR)
      ELSE
        PGLTRRAIL(3,MNUMCR,CURIYR) = sum(PGLTRRAIL(3,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(4,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRRAIL(4,MNUMCR,CURIYR) = PGLTRRAIL(4,MNUMCR,CURIYR) / QGLTRRAIL(4,MNUMCR,CURIYR)
      ELSE
        PGLTRRAIL(4,MNUMCR,CURIYR) = sum(PGLTRRAIL(4,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRSHIP(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRSHIP(1,MNUMCR,CURIYR) = PGFTRSHIP(1,MNUMCR,CURIYR) / QGFTRSHIP(1,MNUMCR,CURIYR)
      ELSE
        PGFTRSHIP(1,MNUMCR,CURIYR) = sum(PGFTRSHIP(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRSHIP(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRSHIP(2,MNUMCR,CURIYR) = PGFTRSHIP(2,MNUMCR,CURIYR) / QGFTRSHIP(2,MNUMCR,CURIYR)
      ELSE
        PGFTRSHIP(2,MNUMCR,CURIYR) = sum(PGFTRSHIP(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRSHIP(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGFTRSHIP(3,MNUMCR,CURIYR) = PGFTRSHIP(3,MNUMCR,CURIYR) / QGFTRSHIP(3,MNUMCR,CURIYR)
      ELSE
        PGFTRSHIP(3,MNUMCR,CURIYR) = sum(PGFTRSHIP(3,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRSHIP(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRSHIP(1,MNUMCR,CURIYR) = PGLTRSHIP(1,MNUMCR,CURIYR) / QGLTRSHIP(1,MNUMCR,CURIYR)
      ELSE
        PGLTRSHIP(1,MNUMCR,CURIYR) = sum(PGLTRSHIP(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRSHIP(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRSHIP(2,MNUMCR,CURIYR) = PGLTRSHIP(2,MNUMCR,CURIYR) / QGLTRSHIP(2,MNUMCR,CURIYR)
      ELSE
        PGLTRSHIP(2,MNUMCR,CURIYR) = sum(PGLTRSHIP(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRSHIP(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        PGLTRSHIP(3,MNUMCR,CURIYR) = PGLTRSHIP(3,MNUMCR,CURIYR) / QGLTRSHIP(3,MNUMCR,CURIYR)
      ELSE
        PGLTRSHIP(3,MNUMCR,CURIYR) = sum(PGLTRSHIP(3,1:9,CURIYR)) / 9.
      ENDIF

! +++ Zero Out US Average Price for all products
      DO IV=1,MNUMP
         MPRC(MNUMCR,IY,IV)=0.
      ENDDO

!   Average the Petroleum Products for each sector.

      DO 111 IR=1,MNUMCR-1
        PRSCM(IR,IY)=PRLCM(IR,IY)
        PRSIN(IR,IY)=PRLIN(IR,IY)
        IF(QRSEL(IR,IY).NE.0.) &
        PRSEL(IR,IY)=PRLEL(IR,IY)  ! ignore high sulfur
        IF(QRSTR(IR,IY).NE.0.) &
        PRSTR(IR,IY)=(PRLTR(IR,IY)*QRLTR(IR,IY)+PRHTR(IR,IY)*QRHTR(IR,IY))/QRSTR(IR,IY)
        IF((QDSRS(IR,IY)+QKSRS(IR,IY)+QLGRS(IR,IY))   .NE.0.0) &
        PTPRS(IR,IY) = (PDSRS(IR,IY)*QDSRS(IR,IY)+PKSRS(IR,IY)* &
           QKSRS(IR,IY)+PLGRS(IR,IY)*QLGRS(IR,IY))/(QDSRS(IR,IY)+ &
           QKSRS(IR,IY)+QLGRS(IR,IY))
        IF((QMGCM(IR,IY)+QDSCM(IR,IY)+QKSCM(IR,IY)+QLGCM(IR,IY)+QRLCM(IR,IY)) .NE. 0.0) &
        PTPCM(IR,IY) = (PMGCM(IR,IY)*QMGCM(IR,IY)+PDSCM(IR,IY)* &
           QDSCM(IR,IY)+PKSCM(IR,IY)*QKSCM(IR,IY)+PLGCM(IR,IY)* &
           QLGCM(IR,IY)+PRLCM(IR,IY)*QRLCM(IR,IY))/(QMGCM(IR,IY)+ &
           QDSCM(IR,IY)+QKSCM(IR,IY)+QLGCM(IR,IY)+QRLCM(IR,IY))
        IF((QMGTR(IR,IY)+QDSTR(IR,IY)+QJFTR(IR,IY)+QLGTR(IR,IY)+ &
            QRLTR(IR,IY)+QRHTR(IR,IY)+QOTTR(IR,IY))    .NE.0.0) &
        PTPTR(IR,IY) = (PMGTR(IR,IY)*QMGTR(IR,IY)+PDSTR(IR,IY)* &
           QDSTR(IR,IY)+PJFTR(IR,IY)*QJFTR(IR,IY)+PLGTR(IR,IY)* &
           QLGTR(IR,IY)+PRLTR(IR,IY)*QRLTR(IR,IY)+PRHTR(IR,IY)* &
           QRHTR(IR,IY)+POTTR(IR,IY)*QOTTR(IR,IY))/(QMGTR(IR,IY)+ &
           QDSTR(IR,IY)+QJFTR(IR,IY)+QLGTR(IR,IY)+QRLTR(IR,IY)+ &
           QRHTR(IR,IY)+QOTTR(IR,IY))
        IF((QMGIN(IR,IY)+QDSIN(IR,IY)+QKSIN(IR,IY)+QLGIN(IR,IY)+ &
            QRLIN(IR,IY)+QPFIN(IR,IY)+QASIN(IR,IY)+QOTIN(IR,IY)).NE.0.0) &
        PTPIN(IR,IY) = (PMGIN(IR,IY)*QMGIN(IR,IY) + PDSIN(IR,IY)*QDSIN(IR,IY) + &
                        PKSIN(IR,IY)*QKSIN(IR,IY)+ &
                        PLGIN(IR,IY)*(QLGIN(IR,IY)-INQLGPF(IR,IY)) + PLGINPF(IR,IY)*INQLGPF(IR,IY) + &
                        PRLIN(IR,IY)*QRLIN(IR,IY) + PPFIN(IR,IY)*QPFIN(IR,IY) + &
                        PASIN(IR,IY)*QASIN(IR,IY) + POTIN(IR,IY)*QOTIN(IR,IY)) / &
                       (QMGIN(IR,IY) + QDSIN(IR,IY) + QKSIN(IR,IY) + QLGIN(IR,IY) + &
                        QRLIN(IR,IY) + QPFIN(IR,IY) + QASIN(IR,IY) + QOTIN(IR,IY))
! recalculate this to exclude PLGINPF at least until we know more about it
        IF((QMGIN(IR,IY)+QDSIN(IR,IY)+QKSIN(IR,IY)+QLGIN(IR,IY)+ &
            QRLIN(IR,IY)+QPFIN(IR,IY)+QASIN(IR,IY)+QOTIN(IR,IY)).NE.0.0) &
        PTPIN(IR,IY) = (PMGIN(IR,IY)*QMGIN(IR,IY) + PDSIN(IR,IY)*QDSIN(IR,IY) + &
                        PKSIN(IR,IY)*QKSIN(IR,IY)+ &
                        PLGIN(IR,IY)*QLGIN(IR,IY)+ &
                        PRLIN(IR,IY)*QRLIN(IR,IY) + PPFIN(IR,IY)*QPFIN(IR,IY) + &
                        PASIN(IR,IY)*QASIN(IR,IY) + POTIN(IR,IY)*QOTIN(IR,IY)) / &
                       (QMGIN(IR,IY) + QDSIN(IR,IY) + QKSIN(IR,IY) + QLGIN(IR,IY) + &
                        QRLIN(IR,IY) + QPFIN(IR,IY) + QASIN(IR,IY) + QOTIN(IR,IY))
        IF((QDSEL(IR,IY)+QRLEL(IR,IY)+QRHEL(IR,IY))   .NE.0.0) &
        PTPEL(IR,IY) = (PDSEL(IR,IY)*QDSEL(IR,IY) + PRSEL(IR,IY)*QRSEL(IR,IY)) / &  !  Using average residual prices
                       (QDSEL(IR,IY)+QRSEL(IR,IY))
 111  CONTINUE

!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!+    Average Prices Across Sectors--Fill the P....AS arrays.
!+
!+    The FUNCTION NUMP_AS(IP,MNUMP) returns the number of component prices for
!+    any of the MNUMP price arrays.  Prices arrays with names not ending in
!+    "AS" (for Across Sector) have 0 as the number of component prices. For
!+    the "AS" arrays, NUMP_AS(IV) returns NUMPAS, the number of prices defined
!+    for product IV.  These NUMPAS component prices arrays are stored as the
!+    NUMPAS consecutive arrays before IV, or from (IV-NUMPAS) to (IV-1).
!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      DO IV=1,MNUMP
         NUMPAS=NUMP_AS(IV,MNUMP)
         IF (NUMPAS.GT.0) THEN
            IQ=PQMATCH(IV,MNUMQ,MNUMP)         ! Get matching QUANTITY product
            DO IC=1,MNUMCR-1
               MPRC(IC,IY,IV)=0.
               IF (MQTY(IC,IY,IQ).GT.0.) THEN  ! Prevent divide by zero
                  DO IP=1,NUMPAS               ! Loop over "NUMPAS" preceeding
                     IPRC=IV-IP                ! products.
                     IQTY=PQMATCH(IPRC,MNUMQ,MNUMP)
                     IF (MPRC(IC,IY,IPRC) .NE. MPRC(IC,IY,IPRC) .OR. MPRC(IC,IY,IPRC) .LT. 0.0000000000001) THEN
                        IF (MPRC(IC,IY,IPRC) .NE. 0.0) MPRC(IC,IY,IPRC) = 0.0000000000001
                     END IF
                     IF (MQTY(IC,IY,IQTY) .NE. MQTY(IC,IY,IQTY) .OR. &
                        (MQTY(IC,IY,IQTY) .LT. 0.0000000000001 .AND. MQTY(IC,IY,IQTY) .GT. -0.0000000000001)) THEN
                        IF (MQTY(IC,IY,IQTY) .LT. 0.0) THEN
                           MQTY(IC,IY,IQTY) = -0.0000000000001
                        ELSE IF (MQTY(IC,IY,IQTY) .GT. 0.0) THEN
                           MQTY(IC,IY,IQTY) = 0.0000000000001
                        END IF
                     END IF
                     MPRC(IC,IY,IV)=MPRC(IC,IY,IV)+MPRC(IC,IY,IPRC)*MQTY(IC,IY,IQTY)
                  ENDDO
                  MPRC(IC,IY,IV)=MPRC(IC,IY,IV)/MQTY(IC,IY,IQ)
               ENDIF
            ENDDO
         ENDIF
      ENDDO

! Recalculate LPG average price to include feedstock price (PLGIN represents heat & power price)
      DO IC = 1,MNUMCR-1
        IF (QLGRS(IC,IY) + QLGCM(IC,IY) + QLGIN(IC,IY) + QLGTR(IC,IY) .NE. 0.0)     PLGAS(IC,IY) = &
                 (PLGIN(IC,IY)*(QLGIN(IC,IY)-INQLGPF(IC,IY)) + PLGINPF(IC,IY)*INQLGPF(IC,IY) + &
                  PLGRS(IC,IY)*QLGRS(IC,IY) + PLGCM(IC,IY)*QLGCM(IC,IY) + PLGTR(IC,IY)*QLGTR(IC,IY)) / &
                 (QLGRS(IC,IY) + QLGCM(IC,IY) + QLGIN(IC,IY) + QLGTR(IC,IY))
      ENDDO

! +++ Average Prices Across Regions, using the corresponding regional quantities as the weights.
      DO IC = 1,MNUMCR - 2
         DO IV=1,MNUMP
            IQ=PQMATCH(IV,MNUMQ,MNUMP)
            IF (MQTY(MNUMCR,IY,IQ).NE.0.) THEN
               MPRC(MNUMCR,IY,IV)=MPRC(MNUMCR,IY,IV)+ &
                   MPRC(IC,IY,IV)*(MQTY(IC,IY,IQ)/MQTY(MNUMCR,IY,IQ))
            ENDIF
         ENDDO
      ENDDO
! Recalculate LPG average price to include feedstock price (PLGIN represents heat & power price)
      IF ((sum(QLGIN(1:9,IY))-sum(INQLGPF(1:9,IY))) .NE. 0.0) &
      PLGIN(MNUMCR,IY) = (PLGIN(1,IY) * (QLGIN(1,IY) - INQLGPF(1,IY)) + &
                          PLGIN(2,IY) * (QLGIN(2,IY) - INQLGPF(2,IY)) + &
                          PLGIN(3,IY) * (QLGIN(3,IY) - INQLGPF(3,IY)) + &
                          PLGIN(4,IY) * (QLGIN(4,IY) - INQLGPF(4,IY)) + &
                          PLGIN(5,IY) * (QLGIN(5,IY) - INQLGPF(5,IY)) + &
                          PLGIN(6,IY) * (QLGIN(6,IY) - INQLGPF(6,IY)) + &
                          PLGIN(7,IY) * (QLGIN(7,IY) - INQLGPF(7,IY)) + &
                          PLGIN(8,IY) * (QLGIN(8,IY) - INQLGPF(8,IY)) + &
                          PLGIN(9,IY) * (QLGIN(9,IY) - INQLGPF(9,IY))) / &
                         (sum(QLGIN(1:9,IY))-sum(INQLGPF(1:9,IY)))

      RETURN
      END
!******************************************************************
!*    SUBROUTINE AVEPASA
!*
!*    AVERAGES ADJUSTED PRICES ACROSS SECTOR AND REGION FOR EPM
!******************************************************************
      SUBROUTINE AVEPASA
      IMPLICIT NONE

      include 'parametr'
      include 'qblk'
      include 'ampblk'
      include 'ncntrl'
      include 'cdsparms'
      include 'coalout'
      include 'indout'
      include 'qonroad'
      include 'aponroad'
!  this is a mistake:  the 'Q' variables are in ngtdmout, but not in angtdm
!  tran.f does indeed use angtdm when it wants the price
!  doing this include combo to get both 'P' and 'Q' variables
!  because of this include combo, need to use 'A' variables for adjusted prices below
      include 'ngtdmout'
      include 'epmngtdm'

      INTEGER IY          ! INDEX FOR YEAR
      INTEGER IC          ! INDEX FOR CENSUS REGION
      INTEGER IV,IP,IPRC  ! INDICES FOR PRICE VARIABLE
      INTEGER IQ,IQTY     ! INDEX FOR QUANTITY VARIABLE
      INTEGER NUMPAS,IR
      EXTERNAL NUMP_AS
      INTEGER NUMP_AS
      EXTERNAL PQMATCH
      INTEGER PQMATCH

      IY = CURIYR

!(*,*)"start AVEPASA()"
!WRITE(*,*)"AVEPASA(), IY=CURIYR,IY=",IY
!WRITE(*,*)"AVEPASA(), MNUMCR=",MNUMCR
!WRITE(*,*)"AVEPASA(), MNUMP=",MNUMP
      PCLGAS(:,IY) = PCLEL(:,IY)    !temporary only!

      INQLGPF(MNUMCR,CURIYR) = 0.0
      PLGINPF(MNUMCR,CURIYR) = 0.0
      QCLGAS(MNUMCR,CURIYR) = 0.0
      PCLGAS(MNUMCR,CURIYR) = 0.0
      PDSTRHWY(MNUMCR,CURIYR) = 0.0
      QGFTRFV(MNUMCR,CURIYR) = 0.0
      QGFTRPV(MNUMCR,CURIYR) = 0.0
      QGLTRFV(MNUMCR,CURIYR) = 0.0
      QGLTRPV(MNUMCR,CURIYR) = 0.0
      QGFTRRAIL(:,MNUMCR,CURIYR) = 0.0
      QGLTRRAIL(:,MNUMCR,CURIYR) = 0.0
      QGFTRSHIP(:,MNUMCR,CURIYR) = 0.0
      QGLTRSHIP(:,MNUMCR,CURIYR) = 0.0
!  because of include combo above, need to use 'A' variables for adjusted prices
      AGFTRFV(MNUMCR,CURIYR) = 0.0
      AGFTRPV(MNUMCR,CURIYR) = 0.0
      AGLTRFV(MNUMCR,CURIYR) = 0.0
      AGLTRPV(MNUMCR,CURIYR) = 0.0
      AGFTRRAIL(:,MNUMCR,CURIYR) = 0.0
      AGLTRRAIL(:,MNUMCR,CURIYR) = 0.0
      AGFTRSHIP(:,MNUMCR,CURIYR) = 0.0
      AGLTRSHIP(:,MNUMCR,CURIYR) = 0.0
      DO IC=1,MNUMCR-2
         INQLGPF(MNUMCR,CURIYR) = INQLGPF(MNUMCR,CURIYR) + INQLGPF(IC,CURIYR)
         PLGINPF(MNUMCR,CURIYR) = PLGINPF(MNUMCR,CURIYR) + PLGINPF(IC,CURIYR) * INQLGPF(IC,CURIYR)
         QCLGAS(MNUMCR,CURIYR) = QCLGAS(MNUMCR,CURIYR) + QCLGAS(IC,CURIYR)
         PCLGAS(MNUMCR,CURIYR) = PCLGAS(MNUMCR,CURIYR) + QCLGAS(IC,CURIYR) * PCLGAS(IC,CURIYR)
         PDSTRHWY(MNUMCR,CURIYR) = PDSTRHWY(MNUMCR,CURIYR) + QDSTRHWY(IC,CURIYR) * PDSTRHWY(IC,CURIYR)
         QGFTRFV(MNUMCR,CURIYR) = QGFTRFV(MNUMCR,CURIYR) + QGFTRFV(IC,CURIYR)
         QGFTRPV(MNUMCR,CURIYR) = QGFTRPV(MNUMCR,CURIYR) + QGFTRPV(IC,CURIYR)
         QGLTRFV(MNUMCR,CURIYR) = QGLTRFV(MNUMCR,CURIYR) + QGLTRFV(IC,CURIYR)
         QGLTRPV(MNUMCR,CURIYR) = QGLTRPV(MNUMCR,CURIYR) + QGLTRPV(IC,CURIYR)
         QGFTRRAIL(1,MNUMCR,CURIYR) = QGFTRRAIL(1,MNUMCR,CURIYR) + QGFTRRAIL(1,IC,CURIYR)
         QGFTRRAIL(2,MNUMCR,CURIYR) = QGFTRRAIL(2,MNUMCR,CURIYR) + QGFTRRAIL(2,IC,CURIYR)
         QGFTRRAIL(3,MNUMCR,CURIYR) = QGFTRRAIL(3,MNUMCR,CURIYR) + QGFTRRAIL(3,IC,CURIYR)
         QGFTRRAIL(4,MNUMCR,CURIYR) = QGFTRRAIL(4,MNUMCR,CURIYR) + QGFTRRAIL(4,IC,CURIYR)
         QGLTRRAIL(1,MNUMCR,CURIYR) = QGLTRRAIL(1,MNUMCR,CURIYR) + QGLTRRAIL(1,IC,CURIYR)
         QGLTRRAIL(2,MNUMCR,CURIYR) = QGLTRRAIL(2,MNUMCR,CURIYR) + QGLTRRAIL(2,IC,CURIYR)
         QGLTRRAIL(3,MNUMCR,CURIYR) = QGLTRRAIL(3,MNUMCR,CURIYR) + QGLTRRAIL(3,IC,CURIYR)
         QGLTRRAIL(4,MNUMCR,CURIYR) = QGLTRRAIL(4,MNUMCR,CURIYR) + QGLTRRAIL(4,IC,CURIYR)
         QGFTRSHIP(1,MNUMCR,CURIYR) = QGFTRSHIP(1,MNUMCR,CURIYR) + QGFTRSHIP(1,IC,CURIYR)
         QGFTRSHIP(2,MNUMCR,CURIYR) = QGFTRSHIP(2,MNUMCR,CURIYR) + QGFTRSHIP(2,IC,CURIYR)
         QGFTRSHIP(3,MNUMCR,CURIYR) = QGFTRSHIP(3,MNUMCR,CURIYR) + QGFTRSHIP(3,IC,CURIYR)
         QGLTRSHIP(1,MNUMCR,CURIYR) = QGLTRSHIP(1,MNUMCR,CURIYR) + QGLTRSHIP(1,IC,CURIYR)
         QGLTRSHIP(2,MNUMCR,CURIYR) = QGLTRSHIP(2,MNUMCR,CURIYR) + QGLTRSHIP(2,IC,CURIYR)
         QGLTRSHIP(3,MNUMCR,CURIYR) = QGLTRSHIP(3,MNUMCR,CURIYR) + QGLTRSHIP(3,IC,CURIYR)
         AGFTRFV(MNUMCR,CURIYR) = AGFTRFV(MNUMCR,CURIYR) + AGFTRFV(IC,CURIYR) * QGFTRFV(IC,CURIYR)
         AGFTRPV(MNUMCR,CURIYR) = AGFTRPV(MNUMCR,CURIYR) + AGFTRPV(IC,CURIYR) * QGFTRPV(IC,CURIYR)
         AGLTRFV(MNUMCR,CURIYR) = AGLTRFV(MNUMCR,CURIYR) + AGLTRFV(IC,CURIYR) * QGLTRFV(IC,CURIYR)
         AGLTRPV(MNUMCR,CURIYR) = AGLTRPV(MNUMCR,CURIYR) + AGLTRPV(IC,CURIYR) * QGLTRPV(IC,CURIYR)
         AGFTRRAIL(1,MNUMCR,CURIYR) = AGFTRRAIL(1,MNUMCR,CURIYR) + AGFTRRAIL(1,IC,CURIYR) * QGFTRRAIL(1,IC,CURIYR)
         AGFTRRAIL(2,MNUMCR,CURIYR) = AGFTRRAIL(2,MNUMCR,CURIYR) + AGFTRRAIL(2,IC,CURIYR) * QGFTRRAIL(2,IC,CURIYR)
         AGFTRRAIL(3,MNUMCR,CURIYR) = AGFTRRAIL(3,MNUMCR,CURIYR) + AGFTRRAIL(3,IC,CURIYR) * QGFTRRAIL(3,IC,CURIYR)
         AGFTRRAIL(4,MNUMCR,CURIYR) = AGFTRRAIL(4,MNUMCR,CURIYR) + AGFTRRAIL(4,IC,CURIYR) * QGFTRRAIL(4,IC,CURIYR)
         AGLTRRAIL(1,MNUMCR,CURIYR) = AGLTRRAIL(1,MNUMCR,CURIYR) + AGLTRRAIL(1,IC,CURIYR) * QGLTRRAIL(1,IC,CURIYR)
         AGLTRRAIL(2,MNUMCR,CURIYR) = AGLTRRAIL(2,MNUMCR,CURIYR) + AGLTRRAIL(2,IC,CURIYR) * QGLTRRAIL(2,IC,CURIYR)
         AGLTRRAIL(3,MNUMCR,CURIYR) = AGLTRRAIL(3,MNUMCR,CURIYR) + AGLTRRAIL(3,IC,CURIYR) * QGLTRRAIL(3,IC,CURIYR)
         AGLTRRAIL(4,MNUMCR,CURIYR) = AGLTRRAIL(4,MNUMCR,CURIYR) + AGLTRRAIL(4,IC,CURIYR) * QGLTRRAIL(4,IC,CURIYR)
         AGFTRSHIP(1,MNUMCR,CURIYR) = AGFTRSHIP(1,MNUMCR,CURIYR) + AGFTRSHIP(1,IC,CURIYR) * QGFTRSHIP(1,IC,CURIYR)
         AGFTRSHIP(2,MNUMCR,CURIYR) = AGFTRSHIP(2,MNUMCR,CURIYR) + AGFTRSHIP(2,IC,CURIYR) * QGFTRSHIP(2,IC,CURIYR)
         AGFTRSHIP(3,MNUMCR,CURIYR) = AGFTRSHIP(3,MNUMCR,CURIYR) + AGFTRSHIP(3,IC,CURIYR) * QGFTRSHIP(3,IC,CURIYR)
         AGLTRSHIP(1,MNUMCR,CURIYR) = AGLTRSHIP(1,MNUMCR,CURIYR) + AGLTRSHIP(1,IC,CURIYR) * QGLTRSHIP(1,IC,CURIYR)
         AGLTRSHIP(2,MNUMCR,CURIYR) = AGLTRSHIP(2,MNUMCR,CURIYR) + AGLTRSHIP(2,IC,CURIYR) * QGLTRSHIP(2,IC,CURIYR)
         AGLTRSHIP(3,MNUMCR,CURIYR) = AGLTRSHIP(3,MNUMCR,CURIYR) + AGLTRSHIP(3,IC,CURIYR) * QGLTRSHIP(3,IC,CURIYR)
      ENDDO
      IF (INQLGPF(MNUMCR,CURIYR) .NE. 0.0) THEN
        PLGINPF(MNUMCR,CURIYR) = PLGINPF(MNUMCR,CURIYR) / INQLGPF(MNUMCR,CURIYR)
      ELSE
        PLGINPF(MNUMCR,CURIYR) = sum(PLGINPF(1:9,CURIYR)) / 9
      ENDIF
      IF (QCLGAS(MNUMCR,CURIYR) .NE. 0.0) THEN
        PCLGAS(MNUMCR,CURIYR) = PCLGAS(MNUMCR,CURIYR) / QCLGAS(MNUMCR,CURIYR)
      ELSE
        PCLGAS(MNUMCR,CURIYR) = sum(PCLGAS(1:9,CURIYR)) / 9
      ENDIF
      IF (QDSTRHWY(MNUMCR,CURIYR) .NE. 0.0) THEN
        PDSTRHWY(MNUMCR,CURIYR) = PDSTRHWY(MNUMCR,CURIYR) / QDSTRHWY(MNUMCR,CURIYR)
      ELSE
        PDSTRHWY(MNUMCR,CURIYR) = sum(PDSTRHWY(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRFV(MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRFV(MNUMCR,CURIYR) = AGFTRFV(MNUMCR,CURIYR) / QGFTRFV(MNUMCR,CURIYR)
      ELSE
        AGFTRFV(MNUMCR,CURIYR) = sum(AGFTRFV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRPV(MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRPV(MNUMCR,CURIYR) = AGFTRPV(MNUMCR,CURIYR) / QGFTRPV(MNUMCR,CURIYR)
      ELSE
        AGFTRPV(MNUMCR,CURIYR) = sum(AGFTRPV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRFV(MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRFV(MNUMCR,CURIYR) = AGLTRFV(MNUMCR,CURIYR) / QGLTRFV(MNUMCR,CURIYR)
      ELSE
        AGLTRFV(MNUMCR,CURIYR) = sum(AGLTRFV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRPV(MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRPV(MNUMCR,CURIYR) = AGLTRPV(MNUMCR,CURIYR) / QGLTRPV(MNUMCR,CURIYR)
      ELSE
        AGLTRPV(MNUMCR,CURIYR) = sum(AGLTRPV(1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRRAIL(1,MNUMCR,CURIYR) = AGFTRRAIL(1,MNUMCR,CURIYR) / QGFTRRAIL(1,MNUMCR,CURIYR)
      ELSE
        AGFTRRAIL(1,MNUMCR,CURIYR) = sum(AGFTRRAIL(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRRAIL(2,MNUMCR,CURIYR) = AGFTRRAIL(2,MNUMCR,CURIYR) / QGFTRRAIL(2,MNUMCR,CURIYR)
      ELSE
        AGFTRRAIL(2,MNUMCR,CURIYR) = sum(AGFTRRAIL(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRRAIL(3,MNUMCR,CURIYR) = AGFTRRAIL(3,MNUMCR,CURIYR) / QGFTRRAIL(3,MNUMCR,CURIYR)
      ELSE
        AGFTRRAIL(3,MNUMCR,CURIYR) = sum(AGFTRRAIL(3,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRRAIL(4,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRRAIL(4,MNUMCR,CURIYR) = AGFTRRAIL(4,MNUMCR,CURIYR) / QGFTRRAIL(4,MNUMCR,CURIYR)
      ELSE
        AGFTRRAIL(4,MNUMCR,CURIYR) = sum(AGFTRRAIL(4,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRRAIL(1,MNUMCR,CURIYR) = AGLTRRAIL(1,MNUMCR,CURIYR) / QGLTRRAIL(1,MNUMCR,CURIYR)
      ELSE
        AGLTRRAIL(1,MNUMCR,CURIYR) = sum(AGLTRRAIL(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRRAIL(2,MNUMCR,CURIYR) = AGLTRRAIL(2,MNUMCR,CURIYR) / QGLTRRAIL(2,MNUMCR,CURIYR)
      ELSE
        AGLTRRAIL(2,MNUMCR,CURIYR) = sum(AGLTRRAIL(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRRAIL(3,MNUMCR,CURIYR) = AGLTRRAIL(3,MNUMCR,CURIYR) / QGLTRRAIL(3,MNUMCR,CURIYR)
      ELSE
        AGLTRRAIL(3,MNUMCR,CURIYR) = sum(AGLTRRAIL(3,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRRAIL(4,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRRAIL(4,MNUMCR,CURIYR) = AGLTRRAIL(4,MNUMCR,CURIYR) / QGLTRRAIL(4,MNUMCR,CURIYR)
      ELSE
        AGLTRRAIL(4,MNUMCR,CURIYR) = sum(AGLTRRAIL(4,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRSHIP(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRSHIP(1,MNUMCR,CURIYR) = AGFTRSHIP(1,MNUMCR,CURIYR) / QGFTRSHIP(1,MNUMCR,CURIYR)
      ELSE
        AGFTRSHIP(1,MNUMCR,CURIYR) = sum(AGFTRSHIP(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRSHIP(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRSHIP(2,MNUMCR,CURIYR) = AGFTRSHIP(2,MNUMCR,CURIYR) / QGFTRSHIP(2,MNUMCR,CURIYR)
      ELSE
        AGFTRSHIP(2,MNUMCR,CURIYR) = sum(AGFTRSHIP(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGFTRSHIP(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGFTRSHIP(3,MNUMCR,CURIYR) = AGFTRSHIP(3,MNUMCR,CURIYR) / QGFTRSHIP(3,MNUMCR,CURIYR)
      ELSE
        AGFTRSHIP(3,MNUMCR,CURIYR) = sum(AGFTRSHIP(3,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRSHIP(1,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRSHIP(1,MNUMCR,CURIYR) = AGLTRSHIP(1,MNUMCR,CURIYR) / QGLTRSHIP(1,MNUMCR,CURIYR)
      ELSE
        AGLTRSHIP(1,MNUMCR,CURIYR) = sum(AGLTRSHIP(1,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRSHIP(2,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRSHIP(2,MNUMCR,CURIYR) = AGLTRSHIP(2,MNUMCR,CURIYR) / QGLTRSHIP(2,MNUMCR,CURIYR)
      ELSE
        AGLTRSHIP(2,MNUMCR,CURIYR) = sum(AGLTRSHIP(2,1:9,CURIYR)) / 9.
      ENDIF
      IF (QGLTRSHIP(3,MNUMCR,CURIYR) .NE. 0.0) THEN
        AGLTRSHIP(3,MNUMCR,CURIYR) = AGLTRSHIP(3,MNUMCR,CURIYR) / QGLTRSHIP(3,MNUMCR,CURIYR)
      ELSE
        AGLTRSHIP(3,MNUMCR,CURIYR) = sum(AGLTRSHIP(3,1:9,CURIYR)) / 9.
      ENDIF

! +++ Zero Out US Average Price for all products
      DO IV=1,MNUMP
         MPRC(MNUMCR,IY,IV)=0.
      ENDDO

!   Average the Petroleum Products for each sector.

      DO 111 IR=1,MNUMCR-1
        PRSCM(IR,IY)=PRLCM(IR,IY)
        PRSIN(IR,IY)=PRLIN(IR,IY)
        IF(QRSEL(IR,IY).NE.0.) &
        PRSEL(IR,IY)=PRLEL(IR,IY)  ! ignore high sulfur
        IF(QRSTR(IR,IY).NE.0.) &
        PRSTR(IR,IY)=(PRLTR(IR,IY)*QRLTR(IR,IY)+PRHTR(IR,IY)*QRHTR(IR,IY))/QRSTR(IR,IY)
        IF((QDSRS(IR,IY)+QKSRS(IR,IY)+QLGRS(IR,IY))   .NE.0.0) &
        PTPRS(IR,IY) = (PDSRS(IR,IY)*QDSRS(IR,IY)+PKSRS(IR,IY)* &
           QKSRS(IR,IY)+PLGRS(IR,IY)*QLGRS(IR,IY))/(QDSRS(IR,IY)+ &
           QKSRS(IR,IY)+QLGRS(IR,IY))
        IF((QMGCM(IR,IY)+QDSCM(IR,IY)+QKSCM(IR,IY)+QLGCM(IR,IY)+QRLCM(IR,IY)) .NE. 0.0) &
        PTPCM(IR,IY) = (PMGCM(IR,IY)*QMGCM(IR,IY)+PDSCM(IR,IY)* &
           QDSCM(IR,IY)+PKSCM(IR,IY)*QKSCM(IR,IY)+PLGCM(IR,IY)* &
           QLGCM(IR,IY)+PRLCM(IR,IY)*QRLCM(IR,IY))/(QMGCM(IR,IY)+ &
           QDSCM(IR,IY)+QKSCM(IR,IY)+QLGCM(IR,IY)+QRLCM(IR,IY))
        IF((QMGTR(IR,IY)+QDSTR(IR,IY)+QJFTR(IR,IY)+QLGTR(IR,IY)+ &
            QRLTR(IR,IY)+QRHTR(IR,IY)+QOTTR(IR,IY))    .NE.0.0) &
        PTPTR(IR,IY) = (PMGTR(IR,IY)*QMGTR(IR,IY)+PDSTR(IR,IY)* &
           QDSTR(IR,IY)+PJFTR(IR,IY)*QJFTR(IR,IY)+PLGTR(IR,IY)* &
           QLGTR(IR,IY)+PRLTR(IR,IY)*QRLTR(IR,IY)+PRHTR(IR,IY)* &
           QRHTR(IR,IY)+POTTR(IR,IY)*QOTTR(IR,IY))/(QMGTR(IR,IY)+ &
           QDSTR(IR,IY)+QJFTR(IR,IY)+QLGTR(IR,IY)+QRLTR(IR,IY)+ &
           QRHTR(IR,IY)+QOTTR(IR,IY))
        IF((QMGIN(IR,IY)+QDSIN(IR,IY)+QKSIN(IR,IY)+QLGIN(IR,IY)+ &
            QRLIN(IR,IY)+QPFIN(IR,IY)+QASIN(IR,IY)+QOTIN(IR,IY)).NE.0.0) &
        PTPIN(IR,IY) = (PMGIN(IR,IY)*QMGIN(IR,IY) + PDSIN(IR,IY)*QDSIN(IR,IY) + &
                        PKSIN(IR,IY)*QKSIN(IR,IY)+ &
                        PLGIN(IR,IY)*(QLGIN(IR,IY)-INQLGPF(IR,IY)) + PLGINPF(IR,IY)*INQLGPF(IR,IY) + &
                        PRLIN(IR,IY)*QRLIN(IR,IY) + PPFIN(IR,IY)*QPFIN(IR,IY) + &
                        PASIN(IR,IY)*QASIN(IR,IY) + POTIN(IR,IY)*QOTIN(IR,IY)) / &
                       (QMGIN(IR,IY) + QDSIN(IR,IY) + QKSIN(IR,IY) + QLGIN(IR,IY) + &
                        QRLIN(IR,IY) + QPFIN(IR,IY) + QASIN(IR,IY) + QOTIN(IR,IY))
! recalculate this to exclude PLGINPF at least until we know more about it
        IF((QMGIN(IR,IY)+QDSIN(IR,IY)+QKSIN(IR,IY)+QLGIN(IR,IY)+ &
            QRLIN(IR,IY)+QPFIN(IR,IY)+QASIN(IR,IY)+QOTIN(IR,IY)).NE.0.0) &
        PTPIN(IR,IY) = (PMGIN(IR,IY)*QMGIN(IR,IY) + PDSIN(IR,IY)*QDSIN(IR,IY) + &
                        PKSIN(IR,IY)*QKSIN(IR,IY)+ &
                        PLGIN(IR,IY)*QLGIN(IR,IY)+ &
                        PRLIN(IR,IY)*QRLIN(IR,IY) + PPFIN(IR,IY)*QPFIN(IR,IY) + &
                        PASIN(IR,IY)*QASIN(IR,IY) + POTIN(IR,IY)*QOTIN(IR,IY)) / &
                       (QMGIN(IR,IY) + QDSIN(IR,IY) + QKSIN(IR,IY) + QLGIN(IR,IY) + &
                        QRLIN(IR,IY) + QPFIN(IR,IY) + QASIN(IR,IY) + QOTIN(IR,IY))
        IF((QDSEL(IR,IY)+QRLEL(IR,IY)+QRHEL(IR,IY))   .NE.0.0) &
        PTPEL(IR,IY) = (PDSEL(IR,IY)*QDSEL(IR,IY) + PRSEL(IR,IY)*QRSEL(IR,IY)) / &  !  Using average residual prices
                       (QDSEL(IR,IY)+QRSEL(IR,IY))
 111  CONTINUE

!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!+    Average Prices Across Sectors--Fill the P....AS arrays.
!+
!+    The FUNCTION NUMP_AS(IP,MNUMP) returns the number of component prices for
!+    any of the MNUMP price arrays.  Prices arrays with names not ending in
!+    "AS" (for Across Sector) have 0 as the number of component prices. For
!+    the "AS" arrays, NUMP_AS(IV) returns NUMPAS, the number of prices defined
!+    for product IV.  These NUMPAS component prices arrays are stored as the
!+    NUMPAS consecutive arrays before IV, or from (IV-NUMPAS) to (IV-1).
!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      DO IV=1,MNUMP
         NUMPAS=NUMP_AS(IV,MNUMP)
         IF (NUMPAS.GT.0) THEN
            IQ=PQMATCH(IV,MNUMQ,MNUMP)         ! Get matching QUANTITY product
            DO IC=1,MNUMCR-1
               MPRC(IC,IY,IV)=0.
               IF (MQTY(IC,IY,IQ).GT.0.) THEN  ! Prevent divide by zero
                  DO IP=1,NUMPAS               ! Loop over "NUMPAS" preceeding
                     IPRC=IV-IP                ! products.
                     IQTY=PQMATCH(IPRC,MNUMQ,MNUMP)
                     MPRC(IC,IY,IV)=MPRC(IC,IY,IV)+MPRC(IC,IY,IPRC)*MQTY(IC,IY,IQTY)
                  ENDDO
                  MPRC(IC,IY,IV)=MPRC(IC,IY,IV)/MQTY(IC,IY,IQ)
               ENDIF
            ENDDO
         ENDIF
      ENDDO

! Recalculate LPG average price to include feedstock price (PLGIN represents heat & power price)
      DO IC = 1,MNUMCR-1
        IF (QLGRS(IC,IY) + QLGCM(IC,IY) + QLGIN(IC,IY) + QLGTR(IC,IY) .NE. 0.0)    PLGAS(IC,IY) = &
                (PLGIN(IC,IY)*(QLGIN(IC,IY)-INQLGPF(IC,IY)) + PLGINPF(IC,IY)*INQLGPF(IC,IY) + &
                 PLGRS(IC,IY)*QLGRS(IC,IY) + PLGCM(IC,IY)*QLGCM(IC,IY) + PLGTR(IC,IY)*QLGTR(IC,IY)) / &
                (QLGRS(IC,IY) + QLGCM(IC,IY) + QLGIN(IC,IY) + QLGTR(IC,IY))
      ENDDO

! +++ Average Prices Across Regions, using the corresponding regional quantities as the weights.
      DO IC = 1,MNUMCR - 2
         DO IV=1,MNUMP
            IQ=PQMATCH(IV,MNUMQ,MNUMP)
            IF (MQTY(MNUMCR,IY,IQ).NE.0.) THEN
               MPRC(MNUMCR,IY,IV)=MPRC(MNUMCR,IY,IV)+ &
                   MPRC(IC,IY,IV)*(MQTY(IC,IY,IQ)/MQTY(MNUMCR,IY,IQ))
            ENDIF
         ENDDO
      ENDDO
! Recalculate LPG average price to include feedstock price (PLGIN represents heat & power price)
      IF ((sum(QLGIN(1:9,IY))-sum(INQLGPF(1:9,IY))) .NE. 0.0) &
      PLGIN(MNUMCR,IY) = (PLGIN(1,IY) * (QLGIN(1,IY) - INQLGPF(1,IY)) + &
                          PLGIN(2,IY) * (QLGIN(2,IY) - INQLGPF(2,IY)) + &
                          PLGIN(3,IY) * (QLGIN(3,IY) - INQLGPF(3,IY)) + &
                          PLGIN(4,IY) * (QLGIN(4,IY) - INQLGPF(4,IY)) + &
                          PLGIN(5,IY) * (QLGIN(5,IY) - INQLGPF(5,IY)) + &
                          PLGIN(6,IY) * (QLGIN(6,IY) - INQLGPF(6,IY)) + &
                          PLGIN(7,IY) * (QLGIN(7,IY) - INQLGPF(7,IY)) + &
                          PLGIN(8,IY) * (QLGIN(8,IY) - INQLGPF(8,IY)) + &
                          PLGIN(9,IY) * (QLGIN(9,IY) - INQLGPF(9,IY))) / &
                         (sum(QLGIN(1:9,IY))-sum(INQLGPF(1:9,IY)))

      RETURN
      END
